Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-06, with the labels that each got.

#90 Fixes #69: DM/managed_instance_group: refactoring
  dm/templates/managed_instance_group/examples/managed_instance_group.yaml
  dm/templates/managed_instance_group/examples/managed_instance_group_healthcheck.yaml
  dm/templates/managed_instance_group/managed_instance_group.py
  dm/templates/managed_instance_group/managed_instance_group.py.schema
  dm/templates/managed_instance_group/tests/integration/managed_instance_group.bats
  dm/templates/managed_instance_group/tests/integration/managed_instance_group.yaml
Labels: DM, cla: yes

#92 Update container-vm to use KT image 2.0.0
  infra/concourse/pipelines/terraform-google-container-vm.yml
Labels: TF, cla: yes, feature request

#93 Add Terraform 0.12 to lint image
  infra/concourse/Makefile.BUILD
  infra/concourse/build/Dockerfile.lint
  infra/concourse/pipelines/terraform-google-address.yml
  infra/concourse/pipelines/terraform-google-cloud-nat.yml
  infra/concourse/pipelines/terraform-google-container-vm.yml
  infra/concourse/pipelines/terraform-google-event-function.yml
  infra/concourse/pipelines/terraform-google-forseti.yml
  infra/concourse/pipelines/terraform-google-jenkins.yml
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
  infra/concourse/pipelines/terraform-google-log-export.yml
  infra/concourse/pipelines/terraform-google-network.yml
  infra/concourse/pipelines/terraform-google-project-factory.yml
  infra/concourse/pipelines/terraform-google-startup-scripts.yml
  infra/concourse/pipelines/terraform-google-vm.yml
  infra/concourse/pipelines/terraform-google-vpn.yml
Labels: TF, cla: yes, feature request

#96 Update diskImage doc to mention valid image
  dm/templates/instance/instance.py.schema
Labels: cla: yes

#97 Add compute.instanceAdmin.v1 for host project
  infra/terraform/test_fixtures/terraform-google-forseti.tf
Labels: TF, cla: yes, feature request

#60 Fixes #55: DM/folder: refactoring
  dm/templates/folder/folder.py
  dm/templates/folder/folder.py.schema
Labels: DM, cla: yes

#89 Fixes #68: DM/instance_template: refactoring
  dm/templates/instance_template/examples/instance_template.yaml
  dm/templates/instance_template/instance_template.py
  dm/templates/instance_template/instance_template.py.schema
  dm/templates/instance_template/tests/integration/instance_template.bats
  dm/templates/instance_template/tests/integration/instance_template.yaml
  dm/templates/instance_template/tests/integration/instance_template_networks.yaml
Labels: DM, cla: yes

#120 Fixes #119: DM/route: refactoring
  dm/templates/route/examples/route.yaml
  dm/templates/route/route.py
  dm/templates/route/route.py.schema
  dm/templates/route/tests/integration/route.yaml
Labels: DM, cla: yes

#126 Fixes #119: DM/route: refactoring
  dm/templates/route/route.py
  dm/templates/route/tests/integration/route.bats
Labels: cla: yes

#150 Fixes #149: DM/project: SA can not be created ("project_id" field is …
  dm/templates/project/project.py
Labels: DM, cla: yes

#160 Added terraform_docs.sh - workaround for HCL2 & terrafrom-docs
  infra/concourse/build/Dockerfile.lint
Labels: TF, cla: yes, feature request

#129 Fixes #116: DM/iam_member: refactoring
  dm/templates/iam_member/iam_member.py.schema
Labels: DM, cla: yes

#100 Fixes #99: DM/firewall: refactoring
  dm/templates/firewall/firewall.py
  dm/templates/firewall/firewall.py.schema
Labels: DM, cla: yes

#102 Fixes #101: DM/bastion: refactoring
  dm/templates/bastion/bastion.py
  dm/templates/bastion/bastion.py.schema
  dm/templates/bastion/tests/integration/bastion.bats
  dm/templates/instance/instance.py
Labels: DM, cla: yes

#104 Fixes #103: DM/backend_service: refactoring
  dm/templates/backend_service/backend_service.py
  dm/templates/backend_service/backend_service.py.schema
  dm/templates/backend_service/examples/backend_service_global.yaml
  dm/templates/backend_service/examples/backend_service_regional.yaml
  dm/templates/backend_service/tests/integration/backend_service.yaml
Labels: DM, cla: yes

#106 Fixes #105: DM/bigquery: refactoring
  dm/templates/bigquery/bigquery_dataset.py
  dm/templates/bigquery/bigquery_dataset.py.schema
  dm/templates/bigquery/bigquery_table.py
  dm/templates/bigquery/bigquery_table.py.schema
  dm/templates/bigquery/tests/integration/bigquery.yaml
Labels: DM, cla: yes

#111 Fixes #110: DM/gke: refactoring
  dm/templates/gke/examples/gke_regional.yaml
  dm/templates/gke/examples/gke_regional_private.yaml
  dm/templates/gke/examples/gke_zonal.yaml
  dm/templates/gke/gke.py
  dm/templates/gke/gke.py.schema
  dm/templates/gke/tests/integration/gke.yaml
Labels: DM, cla: yes

#128 Fixes #117: DM/kms: refactoring
  dm/templates/kms/kms.py
  dm/templates/kms/kms.py.schema
Labels: DM, cla: yes

#125 Fixes #118: DM/pubsub: refactoring
  dm/templates/pubsub/examples/pubsub.yaml
  dm/templates/pubsub/examples/pubsub_push.yaml
  dm/templates/pubsub/pubsub.py
  dm/templates/pubsub/pubsub.py.schema
  dm/templates/pubsub/tests/integration/pubsub.yaml
Labels: DM, cla: yes

#130 Fixes #115: DM/iam_custom_role: refactoring
  dm/templates/iam_custom_role/organization_custom_role.py
  dm/templates/iam_custom_role/organization_custom_role.py.schema
  dm/templates/iam_custom_role/project_custom_role.py
  dm/templates/iam_custom_role/project_custom_role.py.schema
Labels: DM, cla: yes

#133 Fixes #132: DM/ip_reservation: refactoring
  dm/templates/ip_reservation/ip_address.py
  dm/templates/ip_reservation/ip_address.py.schema
  dm/templates/ip_reservation/ip_reservation.py.schema
Labels: DM, cla: yes

#161 Update DOCKER_TAG_LINT to 2.1.0
  infra/concourse/Makefile.BUILD
Labels: TF, cla: yes, feature request

#166 Fixes #162: [DM] IAM_member folder and org support
  dm/templates/iam_member/examples/iam_member.yaml
  dm/templates/iam_member/iam_member.py
  dm/templates/iam_member/iam_member.py.schema
Labels: DM, cla: yes

#131 Fixes #124: DM/healthcheck: refactoring
  dm/templates/healthcheck/healthcheck.py
  dm/templates/healthcheck/healthcheck.py.schema
Labels: DM, cla: yes

#134 Fixes #123: DM/nat_gateway: refactoring
  dm/templates/nat_gateway/nat_gateway.py
  dm/templates/nat_gateway/nat_gateway.py.schema
  dm/templates/nat_gateway/tests/integration/nat_gateway.bats
  dm/templates/route/route.py
  dm/templates/route/tests/integration/route.bats
Labels: DM, cla: yes

#152 Fixes #148: DM/ssl_certificate: refactoring
  dm/templates/ssl_certificate/ssl_certificate.py
  dm/templates/ssl_certificate/ssl_certificate.py.schema
  dm/templates/ssl_certificate/tests/integration/ssl_certificate.yaml
Labels: DM, cla: yes

#155 Fixes #153: DM/url_map: refactoring
  dm/templates/url_map/url_map.py
  dm/templates/url_map/url_map.py.schema
Labels: DM, cla: yes

#164 Lint 2.2.0
  infra/concourse/Makefile.BUILD
  infra/concourse/build/Dockerfile.lint
  infra/concourse/pipelines/terraform-google-container-vm.yml
Labels: TF, cla: yes, feature request

#156 Fixes #154: DM/target_proxy: refactoring
  dm/templates/target_proxy/target_proxy.py
  dm/templates/target_proxy/target_proxy.py.schema
  dm/templates/target_proxy/tests/integration/target_proxy.yaml
Labels: DM, cla: yes

#157 Fixes #141: DM/forwarding_rule: refactoring
  dm/templates/forwarding_rule/forwarding_rule.py
  dm/templates/forwarding_rule/forwarding_rule.py.schema
Labels: DM, cla: yes

#159 Fixes #140: DM/external_load_balancer: refactoring
  dm/templates/external_load_balancer/examples/external_load_balancer_http.yaml
  dm/templates/external_load_balancer/examples/external_load_balancer_https.yaml
  dm/templates/external_load_balancer/examples/external_load_balancer_ssl.yaml
  dm/templates/external_load_balancer/examples/external_load_balancer_tcp.yaml
  dm/templates/external_load_balancer/external_load_balancer.py
  dm/templates/external_load_balancer/external_load_balancer.py.schema
  dm/templates/external_load_balancer/tests/integration/external_load_balancer.bats
  dm/templates/external_load_balancer/tests/integration/external_load_balancer.yaml
Labels: DM, cla: yes

#168 Fixes #143: DM/internal_load_balancer: refactoring
  dm/templates/internal_load_balancer/internal_load_balancer.py
  dm/templates/internal_load_balancer/internal_load_balancer.py.schema
Labels: DM, cla: yes

#169 Fixes #142: DM/haproxy: refactoring
  dm/templates/haproxy/haproxy.py
  dm/templates/haproxy/haproxy.py.schema
Labels: DM, cla: yes

#170 Fixes #137: DM/dataproc: refactoring
  dm/templates/dataproc/dataproc.py
  dm/templates/dataproc/dataproc.py.schema
Labels: DM, cla: yes

#172 Fixes #171: DM: Bug in GKE template examples
  dm/templates/gke/examples/gke_regional.yaml
  dm/templates/gke/examples/gke_regional_private.yaml
  dm/templates/gke/gke.py
  dm/templates/gke/gke.py.schema
Labels: DM, bug, cla: yes
