Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-08, with the labels that each got.

#260 Use Project Factory and configure network in Forseti test fixture
  infra/concourse/pipelines/terraform-google-forseti.yml
  infra/terraform/test_fixtures/terraform-google-forseti.tf
Labels: bug, cla: yes

#250 Developer tools image
  infra/concourse/build/developer-tools/Dockerfile
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/README.md
  infra/concourse/build/developer-tools/build/data/Gemfile
  infra/concourse/build/developer-tools/build/data/Gemfile.lock
  infra/concourse/build/developer-tools/build/data/requirements.txt
  infra/concourse/build/developer-tools/build/home/bash_history
  infra/concourse/build/developer-tools/build/home/bashrc
  infra/concourse/build/developer-tools/build/install_cloud_sdk.sh
  infra/concourse/build/developer-tools/build/install_dependencies.sh
  infra/concourse/build/developer-tools/build/install_gsuite_terraform_provider.sh
  infra/concourse/build/developer-tools/build/install_hadolint.sh
  infra/concourse/build/developer-tools/build/install_kubectl.sh
  infra/concourse/build/developer-tools/build/install_shellcheck.sh
  infra/concourse/build/developer-tools/build/install_terraform.sh
  infra/concourse/build/developer-tools/build/install_terraform_docs.sh
  infra/concourse/build/developer-tools/build/install_verify_boilerplate.sh
  infra/concourse/build/developer-tools/build/scripts/execute_with_credentials.sh
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/basefiles
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_eof_newline
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_python
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_shell
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_terraform
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_whitespace
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/generate_docs
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/golang
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/lint_docker
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_docs.sh
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_validate
  infra/concourse/build/developer-tools/build/scripts/test_integration.sh
  infra/concourse/build/developer-tools/build/scripts/test_lint.sh
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.Dockerfile.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.Makefile.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.go.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.py.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.rb.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.sh.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.tf.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.xml.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.yaml.txt
  infra/concourse/build/developer-tools/build/verify_boilerplate/verify_boilerplate.py
Labels: cla: yes

#261 Patch Forseti infrastructure
  infra/terraform/test_fixtures/terraform-google-forseti.tf
Labels: TF, cla: yes, feature request

#268 Small fixes to templates.
  dm/templates/cloud_tasks/task.py.schema
  dm/templates/ip_reservation/examples/ip_reservation.yaml
  dm/templates/ssl_certificate/examples/ssl_certificate.yaml
Labels: DM, cla: yes

#271 Linking to root directory instead of readme
  README.md
Labels: cla: yes

#286 Add environment preparation scripts to DevEx container
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#285 Helper function to facilitate switch to a 0.12 doc generator
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#282 [WIP] Fixes #269: DM dev branch quality control
  dm/templates/bigquery/bigquery_table.py
  dm/templates/healthcheck/tests/integration/healthcheck.bats
  dm/templates/instance/instance.py
  dm/templates/instance/tests/integration/instance_1_nic.yaml
  dm/templates/instance/tests/integration/instance_2_nics.yaml
  dm/templates/instance_template/tests/integration/instance_template.yaml
  dm/templates/instance_template/tests/integration/instance_template_networks.bats
  dm/templates/instance_template/tests/integration/instance_template_networks.yaml
  dm/templates/shared_vpc_subnet_iam/tests/integration/shared_vpc_subnet_iam.yaml
Labels: DM, cla: yes

#293 Updating changelog
  dm/CHANGELOG.md
  dm/CI/cft_base_contianer/Dockerfile
  dm/CI/cft_base_contianer/cloudbuild.yaml
  dm/CI/cft_schema_runner/Dockerfile
  dm/CI/cft_schema_runner/cloudbuild-test.yaml
  dm/CI/cft_schema_runner/cloudbuild.yaml
  dm/CI/cft_schema_runner/docker-entrypoint.sh
  dm/CI/cft_test_runner/Dockerfile
  dm/CI/cft_test_runner/cloud-foundation-tests.conf
  dm/CI/cft_test_runner/cloudbuild-test.yaml
  dm/CI/cft_test_runner/cloudbuild.yaml
  dm/CI/cft_test_runner/docker-entrypoint.sh
Labels: DM, cla: yes

#292 Container's versions modified for terraform-google-jenkins
  infra/concourse/pipelines/terraform-google-jenkins.yml
Labels: cla: yes

#297 [DM] warning for bastion host sudoers
  dm/templates/bastion/bastion.py.schema
  dm/templates/bastion/tests/integration/bastion.bats
Labels: DM, bug, cla: yes

#257 Isolate a single template from route DM template.
  dm/templates/route/route.py
  dm/templates/route/route.py.schema
  dm/templates/route/single_route.py
  dm/templates/route/single_route.py.schema
Labels: DM, cla: yes

#234 Enable VPN DM template to support static routing.
  dm/templates/vpn/vpn.py
  dm/templates/vpn/vpn.py.schema
Labels: DM, cla: yes

#300 farisjarrah/cloud-sql-docs: Fixed a path error in an Cloud SQL exampl…
  dm/templates/cloud_sql/README.md
  dm/templates/cloud_sql/examples/cloud_sql_postgres.yaml
  dm/templates/cloud_sql/examples/cloud_sql_private_network.yaml
Labels: cla: yes
