Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-11, with the labels that each got.

#425 #407: Create developer-tools-jenkins image
  infra/build/Makefile
  infra/build/developer-tools/build/data/Gemfile
  infra/build/developer-tools/build/data/Gemfile.lock
Labels: cla: yes

#427 Add boilerplate test function
  infra/build/developer-tools/build/verify_boilerplate/test_verify_boilerplate.py
  infra/cloudbuild/test.devtools.yaml
Labels: cla: yes

#401 Update linting task in DevEx image to skip linting on tfvars files.
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: TF, cla: yes

#418 Accept arbitrary content before the license header
  infra/build/Makefile
  infra/build/developer-tools/build/verify_boilerplate/test_verify_boilerplate.py
  infra/build/developer-tools/build/verify_boilerplate/verify_boilerplate.py
Labels: cla: yes

#416 Push dev tools image with extra major version tag
  infra/build/Makefile
Labels: cla: yes, feature request

#440 Add cft-developers group as viewers to test-org
  infra/terraform/test-org/org/folders.tf
  infra/terraform/test-org/org/iam.tf
  infra/terraform/test-org/org/locals.tf
  infra/terraform/test-org/org/outputs.tf
  infra/terraform/test-org/org/versions.tf
Labels: TF, cla: yes, feature request

#419 #382: CLI reference within a value
  cli/deployment/config.go
  cli/deployment/config_test.go
  cli/testdata/cross-ref/dependent-final-expected.yaml
  cli/testdata/cross-ref/dependent-with-refs.yaml
  cli/testdata/cross-ref/main-manifest.yaml
  cli/tests/apply.bats
  cli/tests/create/firewall.yaml
  cli/tests/create/network.yaml
  cli/tests/update/firewall.yaml
  cli/tests/update/network.yaml
Labels: cla: yes

#435 Upgrade folders module to v2.0
  infra/terraform/test-org/org/folders.tf
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#442 [devtools] Fix gsutil
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#366 Adding multistage build to Dockerfile
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/install_terraform.sh
Labels: TF, cla: yes

#446 Enable random project ID for cft-project-manager
  infra/terraform/test-org/test-cleanup/project.tf
Labels: TF, cla: yes

#450 Update gcloud sdk version to 271.0.0
  infra/build/Makefile
Labels: cla: yes

#449 Improve terraform_docs_awk hack which patches terraform-docs on tf 0.12
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_docs.sh
Labels: cla: yes

#414 Cloud Build triggers creation
  infra/terraform/test-org/ci-triggers/backend.tf
  infra/terraform/test-org/ci-triggers/locals.tf
  infra/terraform/test-org/ci-triggers/outputs.tf
  infra/terraform/test-org/ci-triggers/triggers.tf
  infra/terraform/test-org/ci-triggers/versions.tf
  infra/terraform/test-org/org/locals.tf
Labels: TF, cla: yes

#453 Changed GCS bucket 'setIamPolicy' action to virtual type
  dm/templates/gcs_bucket/gcs_bucket.py
  dm/templates/gcs_bucket/gcs_bucket.py.schema
  dm/templates/gcs_bucket/tests/integration/gcs_35_iam_bindings.bats
  dm/templates/gcs_bucket/tests/integration/gcs_35_iam_bindings.yaml
Labels: cla: yes

#454 Add project labels check to the project.py.schema
  dm/templates/project/project.py.schema
Labels: cla: yes

#447 Add subnetwork properties purpose & role
  dm/templates/network/subnetwork.py
  dm/templates/network/subnetwork.py.schema
Labels: DM, cla: yes

#464 Make DM templates compatible with Python3.
  dm/templates/cloud_function/upload.py
  dm/templates/dataproc/dataproc.py
  dm/templates/external_load_balancer/external_load_balancer.py
  dm/templates/firewall/firewall.py
  dm/templates/folder/folder.py
  dm/templates/gcs_bucket/gcs_bucket.py
  dm/templates/iam_member/iam_member.py
  dm/templates/pubsub/pubsub.py
  dm/templates/route/route.py
  dm/templates/runtime_config/runtime_config.py
Labels: DM, cla: yes

#443 Add explicit dependencies to iam members
  dm/CHANGELOG.md
  dm/templates/iam_member/README.md
  dm/templates/iam_member/iam_member.py
  dm/templates/iam_member/iam_member.py.schema
  dm/templates/iam_member/tests/integration/iam_35_members.bats
  dm/templates/iam_member/tests/integration/iam_35_members.yaml
Labels: cla: yes

#460 Add dedicated documentation for CFT scorecard
  cli/README.md
  cli/docs/scorecard.md
Labels: cla: yes

#463 Kubernetes unified monitoring
  dm/CHANGELOG.md
  dm/templates/gke/gke.py.schema
Labels: cla: yes

#461 [DM] Storage update version and changelog
  dm/CHANGELOG.md
  dm/templates/gcs_bucket/README.md
  dm/templates/gcs_bucket/gcs_bucket.py.schema
Labels: DM, cla: yes

#429 CFT Temlate test container supports branch as input
  dm/CI/cft_test_runner/cloudbuild-test.yaml
  dm/CI/cft_test_runner/docker-entrypoint.sh
Labels: DM, cla: yes

#471 Ignore the cache directory when finding files for syntax checking
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#469 Enabled container API instead of compute
  dm/CHANGELOG.md
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: cla: yes

#472 Add standard GitHub labels
  infra/terraform/test-org/github/.gitignore
  infra/terraform/test-org/github/README.md
  infra/terraform/test-org/github/backend.tf
  infra/terraform/test-org/github/labels.tf
  infra/terraform/test-org/github/main.tf
  infra/terraform/test-org/github/outputs.tf
  infra/terraform/test-org/github/versions.tf
Labels: cla: yes

#478 Remove outdated warning and correct the launch date
  dm/templates/cloud_function/README.md
Labels: DM, cla: yes

#479 allow scorecard output to csv and json format
  cli/scorecard/cmd.go
  cli/scorecard/score.go
Labels: cla: yes

#481 [test-org] Create long-living SA which has G-Suite access.
  infra/terraform/test-org/org/gsuite.tf
  infra/terraform/test-org/org/outputs.tf
Labels: TF, cla: yes

#487 Aaron lane fix check terraform
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: TF, bug, cla: yes

#486 Add bindings for gcp-admins
  infra/terraform/test-org/org/folders.tf
  infra/terraform/test-org/org/gsuite.tf
  infra/terraform/test-org/org/iam.tf
  infra/terraform/test-org/org/locals.tf
  infra/terraform/test-org/org/versions.tf
Labels: cla: yes, feature request

#490 [test-org] Grant ci and dev groups rights over gsuite stuff
  infra/terraform/test-org/org/gsuite.tf
Labels: cla: yes
