Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-09, with the labels that each got.

#262 Stand up new test org
  infra/terraform/test-org/org/backend.tf
  infra/terraform/test-org/org/folders.tf
  infra/terraform/test-org/org/iam.tf
  infra/terraform/test-org/org/locals.tf
  infra/terraform/test-org/org/outputs.tf
  infra/terraform/test-org/org/versions.tf
Labels: cla: yes

#302 Add ci folder for `folders` module
  infra/terraform/test-org/org/folders.tf
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#308 Add folderIamAdmin role for 'ci-folders'
  infra/terraform/test-org/org/iam.tf
Labels: cla: yes

#312 [DM] Cloudbuild triggers for CI
  dm/CI/triggers/cft-triggers.py
  dm/CI/triggers/cft-triggers.py.schema
  dm/CI/triggers/cloudbuild_trigger_cft.yaml
  dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml
  dm/templates/cloudbuild/trigger.py
  dm/templates/cloudbuild/trigger.py.schema
  dm/templates/project/project.py
Labels: DM, cla: yes

#276 Update lint-test-image and kitchen-terraform versions for TF12 support.
  infra/concourse/pipelines/terraform-google-startup-scripts.yml
Labels: cla: yes

#318 Fixed #273: DNS Zone example - add FIXME
  dm/templates/dns_managed_zone/examples/dns_managed_zone_private_visibility_config.yaml
Labels: DM, cla: yes

#319 Fixed #135: DM/Add subscription expiration policy to Pub/Sub template
  dm/templates/pubsub/tests/integration/pubsub.bats
  dm/templates/pubsub/tests/integration/pubsub.yaml
Labels: DM, cla: yes

#283 Remove Concourse network config
  infra/concourse/pipelines/terraform-google-network.yml
  infra/terraform/test_fixtures/outputs.tf
  infra/terraform/test_fixtures/terraform-google-network.tf
Labels: cla: yes

#304 Give CI org admin role on test org
  infra/terraform/test-org/org/iam.tf
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#323 CloudSQL Private IP example
  dm/templates/cloud_sql/examples/cloud_sql_private_network.yaml
Labels: DM, cla: yes

#329 Added support to override base path
  infra/concourse/build/developer-tools/Dockerfile
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: TF, cla: yes

#331 Fixed backend_service/examples/backend_service_global.yaml
  dm/templates/backend_service/examples/backend_service_global.yaml
Labels: cla: yes

#328 Create template for the UMIG
  dm/templates/unmanaged_instance_group/README.md
  dm/templates/unmanaged_instance_group/examples/unmanaged_instance_group_add_instance.yaml
  dm/templates/unmanaged_instance_group/examples/unmanaged_instance_group_remove_instance.yaml
  dm/templates/unmanaged_instance_group/tests/integration/unmanaged_instance_group.bats
  dm/templates/unmanaged_instance_group/tests/integration/unmanaged_instance_group.yaml
  dm/templates/unmanaged_instance_group/unmanaged_instance_group.py
  dm/templates/unmanaged_instance_group/unmanaged_instance_group.py.schema
Labels: cla: yes

#342 Fix kitchen_do support for command arguments
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: bug, cla: yes

#345 [DM local testing] Docker image and tutorial for local testing
  dm/docs/template_dev_guide.md
  infra/concourse/build/developer-tools/Dockerfile
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/install_bats.sh
Labels: cla: yes

#314 Scorecard - allow input of CAI files from local filesystem, and take all files in the given bucket or local directory
  cli/go.mod
  cli/scorecard/cmd.go
  cli/scorecard/inventory.go
  cli/scorecard/violations.go
Labels: cla: yes

#349 Release new devtool image: v0.3.0
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/install_bats.sh
Labels: cla: yes

#346 Fixes #321: Instance with private IP example
  dm/templates/instance/README.md
  dm/templates/instance/examples/instance_private.yaml
Labels: DM, cla: yes

#343 Fixes #305: Example Poject template relies on dependencies
  dm/templates/project/README.md
  dm/templates/project/examples/project_standalone.yaml
  dm/templates/project/examples/project_vpc_consumer.yaml
  dm/templates/project/examples/project_vpc_host.yaml
Labels: DM, cla: yes

#348 Fixes #301: Cloud Filestore Template
  dm/templates/cloud_filestore/README.md
  dm/templates/cloud_filestore/cloud_filestore.py
  dm/templates/cloud_filestore/cloud_filestore.py.schema
  dm/templates/cloud_filestore/examples/cloud_filestore.yaml
  dm/templates/cloud_filestore/tests/integration/cloud_filestore.bats
  dm/templates/cloud_filestore/tests/integration/cloud_filestore.yaml
Labels: DM, cla: yes

#327 Make Pubsub template compatible with Python3
  dm/templates/pubsub/pubsub.py
Labels: cla: yes

#352 DM/CLI Hide or list gcloud execution error in case it's expected error
  cli/deployment/api_client.go
Labels: DM, cla: yes

#351 DM/CLI Error pick up the project ID from the YAML file
  cli/cmd/common.go
  cli/deployment/config.go
  cli/deployment/config_test.go
Labels: DM, cla: yes

#358 Folder for CI Testing of Terraform Validator
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes
