Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-12, with the labels that each got.

#492 [DM] IAM Member binding refactor to support on resource binding
  dm/CHANGELOG.md
  dm/templates/iam_member/examples/iam_member_resource.yaml
  dm/templates/iam_member/iam_member.bats
  dm/templates/iam_member/iam_member.py
  dm/templates/iam_member/iam_member.py.schema
  dm/templates/iam_member/tests/integration/iam_member.bats
  dm/templates/iam_member/tests/integration/iam_member.yaml
Labels: DM, cla: yes

#493 Add priority labels to GitHub
  infra/terraform/test-org/github/README.md
  infra/terraform/test-org/github/main.tf
Labels: cla: yes

#495 CFT CLI v0.3.0
  cli/Makefile
  cli/docs/scorecard.md
  cli/go.mod
Labels: cla: yes

#474 Update the dependency on forseti config validator
  cli/go.mod
  cli/go.sum
  cli/scorecard/cmd.go
  cli/scorecard/score.go
  cli/scorecard/violations.go
  cli/validation/forseti.go
  cli/validation/validate.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/api/validator/validator.pb.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/asset/asset.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/asset/proto_util.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/gcv/cf/audit.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/gcv/cf/cf.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/gcv/cf/parsing.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/gcv/validator.go
  cli/vendor/github.com/forseti-security/config-validator/pkg/multierror/multierror.go
  cli/vendor/github.com/spf13/afero/unionFile.go
  cli/vendor/github.com/spf13/cobra/.gitignore
  cli/vendor/github.com/spf13/cobra/README.md
  cli/vendor/github.com/spf13/cobra/bash_completions.go
  cli/vendor/github.com/spf13/cobra/command.go
  cli/vendor/github.com/spf13/cobra/powershell_completions.go
  cli/vendor/github.com/spf13/cobra/powershell_completions.md
  cli/vendor/github.com/spf13/cobra/shell_completions.go
  cli/vendor/github.com/spf13/cobra/zsh_completions.go
  cli/vendor/github.com/spf13/cobra/zsh_completions.md
  cli/vendor/golang.org/x/crypto/openpgp/keys.go
  cli/vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  cli/vendor/golang.org/x/net/http2/frame.go
  cli/vendor/golang.org/x/net/http2/server.go
  cli/vendor/golang.org/x/net/http2/transport.go
  cli/vendor/golang.org/x/net/http2/writesched.go
  cli/vendor/golang.org/x/net/idna/idna.go
  cli/vendor/golang.org/x/net/idna/idna10.0.0.go
  cli/vendor/golang.org/x/net/idna/tables.go
  cli/vendor/golang.org/x/net/idna/tables11.0.0.go
  cli/vendor/golang.org/x/net/idna/tables9.0.0.go
  cli/vendor/modules.txt
Labels: cla: yes

#498 Update Terraform to 0.12.17
  infra/build/Makefile
Labels: TF, cla: yes

#465 Added mssql server template and test
  dm/templates/cloud_sql/README.md
  dm/templates/cloud_sql/cloud_sql.py
  dm/templates/cloud_sql/cloud_sql.py.schema
  dm/templates/cloud_sql/examples/cloud_sql_mssql.yaml
  dm/templates/cloud_sql/tests/integration/cloud_sql_mssql.bats
  dm/templates/cloud_sql/tests/integration/cloud_sql_mssql.yaml
Labels: DM, cla: yes

#476 Update Internal LB template due to backend service schema change
  dm/CHANGELOG.md
  dm/templates/external_load_balancer/examples/external_load_balancer_tcp.yaml
  dm/templates/external_load_balancer/external_load_balancer.py
  dm/templates/external_load_balancer/external_load_balancer.py.schema
  dm/templates/external_load_balancer/tests/integration/external_load_balancer.yaml
  dm/templates/internal_load_balancer/examples/internal_load_balancer.yaml
  dm/templates/internal_load_balancer/internal_load_balancer.py
  dm/templates/internal_load_balancer/internal_load_balancer.py.schema
Labels: DM, cla: yes

#477 Fix database "ipAddress" output
  dm/CHANGELOG.md
  dm/templates/cloud_sql/cloud_sql.py
  dm/templates/cloud_sql/cloud_sql.py.schema
Labels: cla: yes

#470 CloudBuild Trigger support for Github
  dm/CHANGELOG.md
  dm/CI/triggers/cft-triggers.py
  dm/CI/triggers/cft-triggers.py.schema
  dm/CI/triggers/cloudbuild_trigger_cft.yaml
  dm/templates/cloudbuild/trigger.py
  dm/templates/cloudbuild/trigger.py.schema
Labels: DM, cla: yes

#500 resolve static check findings
  cli/cmd/common.go
  cli/report/report.go
  cli/scorecard/score.go
  cli/scorecard/violations.go
Labels: cla: yes

#467 DM Validator unit tests - Fixes 456
  cli/deployment/api_client_test.go
  cli/deployment/config_test.go
  cli/deployment/deployment_test.go
  cli/validation/common_test.go
  cli/validation/converter/compute_firewall_test.go
  cli/validation/converter/compute_instance_test.go
  cli/validation/validate_test.go
Labels: DM, cla: yes

#497 Add Resource Policy DM template
  dm/CHANGELOG.md
  dm/templates/resource_policy/README.md
  dm/templates/resource_policy/examples/resource_policy.yaml
  dm/templates/resource_policy/resource_policy.py
  dm/templates/resource_policy/resource_policy.py.schema
  dm/templates/resource_policy/tests/integration/resource_policy.bats
  dm/templates/resource_policy/tests/integration/resource_policy.yaml
Labels: DM, cla: yes

#510 [test-org] Create a secrets bucket to store gsuite sa key in.
  infra/terraform/test-org/org/gsuite.tf
  infra/terraform/test-org/org/outputs.tf
Labels: cla: yes

#505 [DM] Support SSL_certificates beta features
  dm/CHANGELOG.md
  dm/templates/ssl_certificate/README.md
  dm/templates/ssl_certificate/examples/ssl_certificate_managed.yaml
  dm/templates/ssl_certificate/ssl_certificate.py
  dm/templates/ssl_certificate/ssl_certificate.py.schema
  dm/templates/ssl_certificate/tests/integration/ssl_certificate.bats
  dm/templates/ssl_certificate/tests/integration/ssl_certificate.yaml
Labels: DM, cla: yes

#501 Add targetServiceAccounts to firewall.py.schema
  dm/templates/firewall/firewall.py.schema
Labels: cla: yes

#507 Fixes #506: Network template incorrectly handles empty networks
  dm/templates/network/network.py.schema
Labels: cla: yes

#485 Created Stackdriver notification template
  dm/CHANGELOG.md
  dm/templates/stackdriver_notification_channels/README.md
  dm/templates/stackdriver_notification_channels/examples/stackdriver_notification_channels.yaml
  dm/templates/stackdriver_notification_channels/stackdriver_notification_channels.py
  dm/templates/stackdriver_notification_channels/stackdriver_notification_channels.py.schema
  dm/templates/stackdriver_notification_channels/tests/integration/stackdriver_notification_channels.bats
  dm/templates/stackdriver_notification_channels/tests/integration/stackdriver_notification_channels.yaml
Labels: DM, cla: yes

#503 Added support of bucketPolicyOnly setting for gcs_bucket template
  dm/templates/gcs_bucket/gcs_bucket.py
  dm/templates/gcs_bucket/gcs_bucket.py.schema
  dm/templates/gcs_bucket/tests/integration/gcs_iam_bucket_policy_only.bats
  dm/templates/gcs_bucket/tests/integration/gcs_iam_bucket_policy_only.yaml
Labels: DM, cla: yes

#496 Added log sink template with external bucket
  dm/CHANGELOG.md
  dm/templates/logsink/README.md
  dm/templates/logsink/examples/logsink_new_bq_destination_in_external_project.yaml
  dm/templates/logsink/examples/logsink_new_bucket_destination_in_external_project.yaml
  dm/templates/logsink/examples/logsink_new_pubsub_destination_in_external_project.yaml
  dm/templates/logsink/logsink.py
  dm/templates/logsink/logsink.py.schema
  dm/templates/logsink/tests/integration/logsink_external_project.bats
  dm/templates/logsink/tests/integration/logsink_external_project.yaml
Labels: DM, cla: yes

#509 Add varable to set additional dirs to exclude from lints
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#518 Add list of SSL certs to the target proxy in the external LB template
  dm/templates/external_load_balancer/external_load_balancer.py.schema
Labels: cla: yes

#521 Allow CFT Scorecard to read JSON metadata from Stdin
  cli/go.mod
  cli/scorecard/cmd.go
  cli/scorecard/inventory.go
  cli/scorecard/violations.go
Labels: cla: yes

#523 fix ability to add multiple directories to ignore in linting
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#527 Fix EXCLUDE_LINT_DIRS unbound variable. Fix #526.
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#522 allow passing in validator directly to construct ScoringConfig
  cli/scorecard/score.go
  cli/scorecard/violations.go
Labels: cla: yes
