Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-10, with the labels that each got.

#315 Inventory reporting feature under new 'report' subcommand
  cli/README.md
  cli/cmd/root.go
  cli/go.mod
  cli/report/cmd.go
  cli/report/convert.go
  cli/report/report.go
  reports/sample/README.md
  reports/sample/data.rego
  reports/sample/iam.rego
  reports/sample/network.rego
  reports/sample/util.rego
  reports/sample/vm.rego
Labels: TF, cla: yes

#354 Add bats-support, bats-mock, bats-assert libraries
  infra/concourse/build/developer-tools/Dockerfile
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/install_bats.sh
Labels: TF, cla: yes

#359 DM/CLI Could not resolve cross-deployment reference in case of hierarchical resource outputs
  cli/deployment/api_client.go
  cli/deployment/config.go
  cli/deployment/config_test.go
  cli/deployment/order.go
  cli/testdata/cross-ref/dependent-final-expected.yaml
  cli/testdata/cross-ref/dependent-with-refs.yaml
  cli/testdata/cross-ref/main-manifest.yaml
  cli/testdata/deployment/describe/done.yaml
  cli/testdata/deployment/describe/error.yaml
  cli/testdata/deployment/describe/not-found.txt
  cli/testdata/deployment/describe/pending.yaml
  cli/testdata/deployment/describe/running.yaml
Labels: DM, cla: yes

#350 DM/CLI Not fail on cross-deployment references to existing deployments
  cli/Makefile
  cli/deployment/api_client.go
  cli/deployment/api_client_test.go
  cli/deployment/config.go
Labels: DM, cla: yes

#365 Added JPEG and PNG file extentions to exclude from `find_files` function
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#368 Add SA activation to init_credentials function
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#356 Only add test-base-path to main kitchen commands
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: TF, cla: yes

#326 Add build, release instructions; fix header size
  infra/concourse/build/developer-tools/README.md
Labels: TF, cla: yes

#317 Fixes #274: Invalid example - Cloud build trigger
  dm/templates/cloudbuild/cloudbuild.py.schema
  dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml
  dm/templates/cloudbuild/tests/integration/cloudbuild.bats
  dm/templates/cloudbuild/tests/integration/cloudbuild.yaml
  dm/templates/cloudbuild/trigger.py
  dm/templates/cloudbuild/trigger.py.schema
Labels: DM, cla: yes

#372 [DM] fixing GKE schema
  dm/templates/gke/gke.py.schema
Labels: DM, bug, cla: yes

#371 Fix lint test do not fail
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#373 Exclude autogen and shared fixtures dirs from find_files
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#377 minor fixes to readme; and hide bucket option for now
  cli/README.md
  cli/report/cmd.go
Labels: cla: yes

#363 [DM] Project example schema fix
  dm/templates/project/examples/project_vpc_host.yaml
Labels: DM, bug, cla: yes

#322 Adding ProjectNumber to project template output and schema
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: DM, cla: yes

#380 Fix generate_docs for default objects with null values
  infra/concourse/build/developer-tools/Makefile
  infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_docs.sh
Labels: cla: yes

#347 Remove the Event Function pipeline
  infra/concourse/pipelines/terraform-google-event-function.yml
Labels: TF, cla: yes

#383 [DM] fixing IAM member binding schema
  dm/templates/iam_member/iam_member.py.schema
Labels: DM, bug, cla: yes

#384 [DM] fixing IAM member binding schema
  dm/templates/iam_member/iam_member.py.schema
Labels: DM, bug, cla: yes

#388 Exclude *.svg files from lint checks
  infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#389 Move Developer Tools out of Concourse
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/Makefile
  infra/build/developer-tools/README.md
  infra/build/developer-tools/build/data/Gemfile
  infra/build/developer-tools/build/data/Gemfile.lock
  infra/build/developer-tools/build/data/requirements.txt
  infra/build/developer-tools/build/home/bash_history
  infra/build/developer-tools/build/home/bashrc
  infra/build/developer-tools/build/install_bats.sh
  infra/build/developer-tools/build/install_cloud_sdk.sh
  infra/build/developer-tools/build/install_dependencies.sh
  infra/build/developer-tools/build/install_gsuite_terraform_provider.sh
  infra/build/developer-tools/build/install_hadolint.sh
  infra/build/developer-tools/build/install_kubectl.sh
  infra/build/developer-tools/build/install_shellcheck.sh
  infra/build/developer-tools/build/install_terraform.sh
  infra/build/developer-tools/build/install_terraform_docs.sh
  infra/build/developer-tools/build/install_verify_boilerplate.sh
  infra/build/developer-tools/build/scripts/execute_with_credentials.sh
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/basefiles
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/check_eof_newline
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/check_python
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/check_shell
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/check_terraform
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/check_whitespace
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/generate_docs
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/golang
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/lint_docker
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_docs.sh
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_validate
  infra/build/developer-tools/build/scripts/test_integration.sh
  infra/build/developer-tools/build/scripts/test_lint.sh
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.Dockerfile.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.Makefile.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.go.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.py.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.rb.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.sh.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.tf.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.xml.txt
  infra/build/developer-tools/build/verify_boilerplate/boilerplate/boilerplate.yaml.txt
  infra/build/developer-tools/build/verify_boilerplate/verify_boilerplate.py
Labels: cla: yes

#393 add gcloud module
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#394 Make tf validator project ID random
  infra/terraform/test-org/tf-validator/project.tf
Labels: cla: yes

#395 Exclude autogen directory from check_documentation
  infra/build/developer-tools/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: bug, cla: yes

#378 update scorecard readme and cli help
  cli/README.md
  cli/scorecard/cmd.go
Labels: TF, cla: yes

#396 Update README.md
  dm/templates/project/README.md
Labels: cla: yes

#398 add gz to list of files you can ignore checking whitespace and newlin…
  infra/build/developer-tools/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#375 Remove old Concourse pipelines
  infra/concourse/pipelines/terraform-google-cloud-nat.yml
  infra/concourse/pipelines/terraform-google-container-vm.yml
  infra/concourse/pipelines/terraform-google-folders.yml
  infra/concourse/pipelines/terraform-google-forseti.yml
  infra/concourse/pipelines/terraform-google-iam.yml
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
  infra/concourse/pipelines/terraform-google-log-export.yml
  infra/concourse/pipelines/terraform-google-project-factory.yml
  infra/concourse/pipelines/terraform-google-service-accounts.yml
  infra/concourse/pipelines/terraform-google-startup-scripts.yml
  infra/concourse/pipelines/terraform-google-vm.yml
Labels: TF, cla: yes

#306 Add script for deleting all projects within a folder
  infra/utils/delete-projects.py
Labels: TF, cla: yes

#392 [DM] ELB examples fixed to match strict backend schema
  dm/templates/external_load_balancer/examples/external_load_balancer_http.yaml
  dm/templates/external_load_balancer/examples/external_load_balancer_https.yaml
  dm/templates/external_load_balancer/examples/external_load_balancer_ssl.yaml
  dm/templates/external_load_balancer/examples/external_load_balancer_tcp.yaml
Labels: DM, cla: yes

#385 Ocsig gke shared vpc 7
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: DM, cla: yes

#404 SharedVPC IAM support on the folder level
  dm/CHANGELOG.md
  dm/templates/project/README.md
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: DM, cla: yes, feature request

#410 exempt test/source.sh from lint header checks
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#412 added the dependsOn to the example
  dm/templates/bigquery/examples/bigquery.yaml
Labels: cla: yes

#411 Update folder.py.schema
  dm/templates/folder/folder.py.schema
Labels: cla: yes

#413 [DM] Allowing sigle regions for BQ dataset in schema
  dm/CHANGELOG.md
  dm/templates/bigquery/bigquery_dataset.py.schema
Labels: DM, bug, cla: yes

#415 [developer-tools] Automatically pipe terraform outputs from setup folder into kitchen_do
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/scripts/export_tf_outputs.py
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#409 #407: Create developer-tools-jenkins image
  infra/build/Makefile
  infra/build/developer-tools-jenkins/Dockerfile
  infra/build/developer-tools-jenkins/build/install_packer.sh
Labels: TF, cla: yes, feature request

#370 Add important IP ranges
  dm/CHANGELOG.md
  dm/helpers/google_netblock_ip_ranges/README.md
  dm/helpers/google_netblock_ip_ranges/examples/google_netblock_ip_ranges_example.yaml
  dm/helpers/google_netblock_ip_ranges/google_netblock_ip_ranges.py
  dm/helpers/google_netblock_ip_ranges/google_netblock_ip_ranges.yaml
Labels: DM, cla: yes
