Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-05, with the labels that each got.

#15 template_dev_guide.md script fix, basic .gitignore added
  .gitignore
  dm/.gitignore
  dm/docs/template_dev_guide.md
Labels: DM

#16 Fixed Managed DNS issue: added same value for element reference and m…
  .gitignore
  dm/templates/dns_managed_zone/dns_managed_zone.py
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
  dm/templates/dns_managed_zone/tests/integration/dns_managed_zone.yaml
Labels: DM

#4 Resolved issues with instance schema naming not aligned with api
  dm/templates/instance/instance.py.schema
  dm/templates/instance_template/instance_template.py.schema
  dm/templates/managed_instance_group/managed_instance_group.py.schema
Labels: DM

#26 Fix/dm 363
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: DM, bug

#35 Initial PoC for templates unit tests
  dm/Makefile
  dm/docs/template_dev_guide.md
  dm/requirements/development.txt
  dm/templates/project/tests/schemas/invalid_project.yaml
  dm/tests/run-tests
  dm/tests/templates/__init__.py
  dm/tests/templates/conftest.py
  dm/tests/templates/test_schemas.py
  dm/tox.ini
Labels: DM, cla: yes

#34 Fixes project.py schema
  dm/templates/project/project.py.schema
Labels: DM

#36 Fixes #446 GKE template output error (nodeIpv4CidrSize)
  dm/templates/gke/gke.py
Labels: cla: yes

#38 Fixed GKE outputs: #436 GKE >1.12 versions are not creating ClientCer…
  dm/templates/gke/gke.py
Labels: DM, cla: yes

#33 Initial implementation of CFT cli tool on golang
  cli/Makefile
  cli/README.md
  cli/bin/.gitignore
  cli/cmd/root.go
  cli/cmd/root_test.go
  cli/cmd/version.go
  cli/cmd/version_test.go
  cli/go.mod
  cli/go.sum
  cli/main.go
Labels: cla: yes

#31 enh 434: instance template should support multiple NICs
  dm/templates/instance/examples/instance.yaml
  dm/templates/instance/instance.py
  dm/templates/instance/instance.py.schema
  dm/templates/instance/tests/integration/instance_1_nic.bats
  dm/templates/instance/tests/integration/instance_1_nic.yaml
  dm/templates/instance/tests/integration/instance_2_nics.bats
  dm/templates/instance/tests/integration/instance_2_nics.yaml
  dm/templates/instance/tests/integration/instance_template/instance_template.bats
  dm/templates/instance/tests/integration/instance_template/instance_template.yaml
  dm/templates/instance_template/examples/instance_template.yaml
  dm/templates/instance_template/instance_template.py
  dm/templates/instance_template/instance_template.py.schema
  dm/templates/instance_template/tests/integration/instance_template_networks.bats
  dm/templates/instance_template/tests/integration/instance_template_networks.yaml
Labels: DM, cla: yes

#42 Disallowed unexpected properties in json schema
  dm/templates/autoscaler/autoscaler.py.schema
  dm/templates/backend_service/backend_service.py.schema
  dm/templates/bastion/bastion.py.schema
  dm/templates/bigquery/bigquery_dataset.py.schema
  dm/templates/bigquery/bigquery_table.py.schema
  dm/templates/cloud_function/cloud_function.py.schema
  dm/templates/cloud_router/cloud_router.py.schema
  dm/templates/cloud_spanner/cloud_spanner.py.schema
  dm/templates/cloud_sql/cloud_sql.py.schema
  dm/templates/cloud_tasks/queue.py.schema
  dm/templates/cloudbuild/cloudbuild.py.schema
  dm/templates/dataproc/dataproc.py.schema
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
  dm/templates/dns_records/dns_records.py.schema
  dm/templates/external_load_balancer/external_load_balancer.py.schema
  dm/templates/firewall/firewall.py.schema
  dm/templates/folder/folder.py.schema
  dm/templates/forseti/client.py.schema
  dm/templates/forwarding_rule/forwarding_rule.py.schema
  dm/templates/gcs_bucket/gcs_bucket.py.schema
  dm/templates/gke/gke.py.schema
  dm/templates/haproxy/haproxy.py.schema
  dm/templates/healthcheck/healthcheck.py.schema
  dm/templates/iam_custom_role/organization_custom_role.py.schema
  dm/templates/iam_custom_role/project_custom_role.py.schema
  dm/templates/iam_member/iam_member.py.schema
  dm/templates/instance/instance.py.schema
  dm/templates/instance_template/instance_template.py.schema
  dm/templates/interconnect/interconnect.py.schema
  dm/templates/interconnect_attachment/interconnect_attachment.py.schema
  dm/templates/internal_load_balancer/internal_load_balancer.py.schema
  dm/templates/ip_reservation/ip_address.py.schema
  dm/templates/ip_reservation/ip_reservation.py.schema
  dm/templates/kms/kms.py.schema
  dm/templates/logsink/logsink.py.schema
  dm/templates/managed_instance_group/managed_instance_group.py.schema
  dm/templates/nat_gateway/nat_gateway.py.schema
  dm/templates/network/network.py.schema
  dm/templates/network/subnetwork.py.schema
  dm/templates/network_peering/network_peering.py.schema
  dm/templates/org_policy/org_policy.py.schema
  dm/templates/project/project.py.schema
  dm/templates/pubsub/pubsub.py.schema
  dm/templates/route/route.py.schema
  dm/templates/runtime_config/runtime_config.py.schema
  dm/templates/runtime_config/variable.py.schema
  dm/templates/runtime_config/waiter.py.schema
  dm/templates/shared_vpc_subnet_iam/shared_vpc_subnet_iam.py.schema
  dm/templates/ssl_certificate/ssl_certificate.py.schema
  dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py.schema
  dm/templates/target_proxy/target_proxy.py.schema
  dm/templates/url_map/url_map.py.schema
  dm/templates/vpn/vpn.py.schema
Labels: DM, cla: yes

#44 Add the required role to manage firewall rules in network module tests
  infra/terraform/test_fixtures/terraform-google-network.tf
Labels: cla: yes

#46 Fix/dm 434
  dm/.gitignore
  dm/templates/instance/instance.py.schema
  dm/templates/instance_template/instance_template.py.schema
  dm/templates/managed_instance_group/examples/managed_instance_group.yaml
  dm/templates/managed_instance_group/managed_instance_group.py.schema
Labels: DM, cla: yes

#50 Pin Google providers to 2.7.0
  infra/terraform/test_fixtures/main.tf
Labels: TF, cla: yes

#41 added CI pipeline for vm module
  infra/concourse/pipelines/terraform-google-vm.yml
  infra/terraform/test_fixtures/outputs.tf
  infra/terraform/test_fixtures/terraform-google-vm.tf
Labels: TF, cla: yes

#71 added mandatory parameter: REGION
  infra/concourse/pipelines/terraform-google-vm.yml
  infra/terraform/test_fixtures/terraform-google-vm.tf
Labels: cla: yes

#73 Extend VM project ID to meet length requirement
  infra/terraform/test_fixtures/terraform-google-vm.tf
Labels: TF, bug, cla: yes

#74 Correct VM Kubernetes secret name
  infra/terraform/test_fixtures/terraform-google-vm.tf
Labels: TF, bug, cla: yes

#79 ci: updated region to conform it to the one in tests
  infra/concourse/pipelines/terraform-google-vm.yml
Labels: cla: yes

#76 Don't require logObjectPrefix for buckets
  dm/templates/gcs_bucket/gcs_bucket.py.schema
Labels: DM, cla: yes

#64 Fixes #51: DM/cloud_router: refactoring
  dm/templates/cloud_router/cloud_router.py
  dm/templates/cloud_router/cloud_router.py.schema
  dm/templates/cloud_router/tests/schemas/invalid_additional_options.yaml
  dm/templates/cloud_router/tests/schemas/valid_basic.yaml
Labels: DM, cla: yes

#37 Test fixture for terraform-google-jenkins added
  infra/concourse/build/Dockerfile.kitchen-terraform
  infra/terraform/test_fixtures/terraform-google-jenkins.tf
Labels: TF, cla: yes

#80 Kitchen-Terraform Docker image 1.3.0
  infra/concourse/Makefile.BUILD
  infra/concourse/pipelines/terraform-google-jenkins.yml
Labels: TF, cla: yes, feature request

#81 Terraform v0.12 Docker images
  infra/concourse/Makefile.BUILD
  infra/concourse/build/data/Gemfile
  infra/concourse/build/data/Gemfile.lock
Labels: TF, cla: yes, feature request

#59 Fixes #57: DM/project: refactoring
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: DM, cla: yes

#83 Fixes #66: DM/gcs_bucket: refactoring
  dm/templates/gcs_bucket/gcs_bucket.py
  dm/templates/gcs_bucket/gcs_bucket.py.schema
Labels: DM, cla: yes

#61 Fixes #56: DM/network: refactoring
  dm/templates/network/network.py
  dm/templates/network/network.py.schema
  dm/templates/network/subnetwork.py
  dm/templates/network/subnetwork.py.schema
  dm/templates/network/tests/schemas/invalid_subnets.yaml
  dm/templates/network/tests/schemas/valid_auto.yaml
  dm/templates/network/tests/schemas/valid_subnets.yaml
Labels: DM, cla: yes

#62 Fixes #54: DM/cloud_sql: refactoring
  dm/templates/cloud_sql/cloud_sql.py
  dm/templates/cloud_sql/cloud_sql.py.schema
  dm/templates/cloud_sql/tests/schemas/invalid_additional_options.yaml
  dm/templates/cloud_sql/tests/schemas/invalid_additional_options_nested.yaml
  dm/templates/cloud_sql/tests/schemas/invalid_missing_region.yaml
  dm/templates/cloud_sql/tests/schemas/invalid_missing_tier.yaml
  dm/templates/cloud_sql/tests/schemas/valid_basic.yaml
  dm/templates/cloud_sql/tests/schemas/valid_complex.yaml
Labels: DM, cla: yes

#63 Fixes #53: DM/cloud_spanner: refactoring
  dm/templates/cloud_spanner/cloud_spanner.py
  dm/templates/cloud_spanner/cloud_spanner.py.schema
  dm/templates/cloud_spanner/tests/schemas/invalid_additional_options.yaml
  dm/templates/cloud_spanner/tests/schemas/valid_basic.yaml
  dm/templates/cloud_spanner/tests/schemas/valid_complex.yaml
Labels: DM, cla: yes

#84 Fixes #70: DM/instance: refactoring
  dm/templates/instance/examples/instance.yaml
  dm/templates/instance/instance.py
  dm/templates/instance/instance.py.schema
Labels: DM, cla: yes

#82 Fixes #67: DM/autoscaler: refactoring
  dm/templates/autoscaler/autoscaler.py
  dm/templates/autoscaler/autoscaler.py.schema
Labels: DM, cla: yes

#65 Fixes #52: DM/cloud_function: refactoring
  dm/templates/cloud_function/cloud_function.py
  dm/templates/cloud_function/cloud_function.py.schema
  dm/templates/cloud_function/upload.py
Labels: DM, cla: yes

#87 Support requesterPays for GCS buckets
  dm/templates/gcs_bucket/gcs_bucket.py
  dm/templates/gcs_bucket/gcs_bucket.py.schema
Labels: cla: yes

#88 Start a CODEOWNERS file
  CODEOWNERS
Labels: cla: yes
