Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2019-07, with the labels that each got.

#176 DM/dns_managed_zone: refactoring #138
  dm/templates/dns_managed_zone/README.md
  dm/templates/dns_managed_zone/dns_managed_zone.py
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
  dm/templates/dns_managed_zone/examples/dns_managed_zone.yaml
  dm/templates/dns_managed_zone/examples/dns_managed_zone_private.yaml
  dm/templates/dns_managed_zone/examples/dns_managed_zone_private_visibility_config.yaml
  dm/templates/dns_managed_zone/examples/dns_managed_zone_public.yaml
  dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats
  dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.yaml
  dm/templates/dns_managed_zone/tests/integration/dns_mz_private.bats
  dm/templates/dns_managed_zone/tests/integration/dns_mz_private.yaml
  dm/templates/dns_managed_zone/tests/integration/dns_mz_prvt_vsblt_cfg.bats
  dm/templates/dns_managed_zone/tests/integration/dns_mz_prvt_vsblt_cfg.yaml
  dm/templates/dns_managed_zone/tests/integration/dns_mz_public.bats
  dm/templates/dns_managed_zone/tests/integration/dns_mz_public.yaml
  dm/templates/dns_managed_zone/tests/integration/dns_mz_simple.bats
  dm/templates/dns_managed_zone/tests/integration/dns_mz_simple.yaml
Labels: DM, cla: yes, feature request

#187 [DM] Patch IAM member to projectID
  dm/templates/iam_member/iam_member.py
Labels: DM, cla: yes

#178 Adding workload-metadata-config-local test
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
Labels: TF, cla: yes, feature request

#86 DM/cli Sprint 2 stories
  cli/Makefile
  cli/README.md
  cli/cmd/create.go
  cli/cmd/doc.go
  cli/cmd/root.go
  cli/cmd/root_test.go
  cli/deployment/api_client.go
  cli/deployment/api_client_test.go
  cli/deployment/config.go
  cli/deployment/config_test.go
  cli/deployment/deployment.go
  cli/deployment/doc.go
  cli/deployment/order.go
  cli/deployment/order_test.go
  cli/deployment/utils.go
  cli/deployment/utils_test.go
  cli/go.mod
  cli/go.sum
  cli/main.go
  cli/testdata/config/custom-fields.yaml
  cli/testdata/config/simple.yaml
  cli/testdata/cross-ref/dependent.yaml
  cli/testdata/cross-ref/main.yaml
  cli/testdata/deployment/api-client-describe.yaml
  cli/testdata/deployment/api-describe-manifest.yaml
  infra/concourse/Makefile.BUILD
  infra/concourse/build/Dockerfile.lint
  infra/concourse/pipelines/terraform-google-container-vm.yml
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
Labels: DM, cla: yes

#199 Adding upstream nameservers tests to ci
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
Labels: TF, cla: yes, feature request

#122 Update network for Terraform 0.12
  infra/concourse/Makefile.BUILD
  infra/concourse/build/Dockerfile.lint
  infra/concourse/pipelines/terraform-google-network.yml
Labels: TF, cla: yes

#204 Fix couple of typographical errors
  cli/README.md
  cli/cmd/root.go
Labels: cla: yes

#206 Fix prerequisites Makefile target to align with docs and help
  dm/Makefile
  dm/docs/userguide.md
Labels: cla: yes

#213 Update Project Factory integration test image
  infra/concourse/pipelines/terraform-google-project-factory.yml
Labels: TF, cla: no, feature request

#198 Update terraform-google-cloud-nat CI workflow
  infra/concourse/pipelines/terraform-google-cloud-nat.yml
Labels: TF, cla: yes, feature request

#217 Add kubectl to kitchen-terraform image
  infra/concourse/Makefile.BUILD
  infra/concourse/build/Dockerfile.kitchen-terraform
Labels: cla: yes

#222 Fixes #175: IAM needs to depends on SA existance
  dm/templates/iam_member/iam_member.py
  dm/templates/iam_member/iam_member.py.schema
  dm/templates/project/project.py
Labels: DM, cla: yes

#218 Remove intermediary kitchen-terraform image build steps from terraform-google-kubernetes-engine CI pipeline
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
Labels: TF, cla: yes, feature request

#216 Update docker images for TF 0.12.3
  infra/concourse/Makefile.BUILD
  infra/concourse/build/Dockerfile.lint
  infra/concourse/pipelines/terraform-google-project-factory.yml
Labels: cla: yes

#225 Update docker images for network module
  infra/concourse/pipelines/terraform-google-network.yml
Labels: cla: yes

#203 [WIP] CFT cli integration branch
  cli/Makefile
  cli/README.md
  cli/cmd/create.go
  cli/cmd/doc.go
  cli/cmd/root.go
  cli/cmd/root_test.go
  cli/deployment/api_client.go
  cli/deployment/api_client_test.go
  cli/deployment/config.go
  cli/deployment/config_test.go
  cli/deployment/deployment.go
  cli/deployment/doc.go
  cli/deployment/order.go
  cli/deployment/order_test.go
  cli/deployment/utils.go
  cli/deployment/utils_test.go
  cli/go.mod
  cli/go.sum
  cli/main.go
  cli/testdata/config/custom-fields.yaml
  cli/testdata/config/simple.yaml
  cli/testdata/cross-ref/dependent.yaml
  cli/testdata/cross-ref/main.yaml
  cli/testdata/deployment/api-client-describe.yaml
  cli/testdata/deployment/api-describe-manifest.yaml
Labels: cla: yes

#195 Fixes #183: DM/interconnect_attachment: refactoring
  dm/templates/interconnect_attachment/interconnect_attachment.py
  dm/templates/interconnect_attachment/interconnect_attachment.py.schema
Labels: DM, cla: yes

#201 Fixes #184: DM/runtime_config: refactoring
  dm/templates/runtime_config/examples/runtime_config.yaml
  dm/templates/runtime_config/runtime_config.py
  dm/templates/runtime_config/runtime_config.py.schema
  dm/templates/runtime_config/tests/integration/runtime_config.yaml
  dm/templates/runtime_config/variable.py
  dm/templates/runtime_config/variable.py.schema
  dm/templates/runtime_config/waiter.py
  dm/templates/runtime_config/waiter.py.schema
Labels: DM, cla: yes

#196 Fixes #182: DM/interconnect: refactoring
  dm/templates/interconnect/interconnect.py
  dm/templates/interconnect/interconnect.py.schema
Labels: DM, cla: yes

#194 Fixed Backward Compatibility Support. Fixed pydocstyle D210, D202. #138
  dm/templates/dns_managed_zone/dns_managed_zone.py
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
  dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats
Labels: DM, cla: yes

#197 Refactored dns_records template #139
  dm/templates/dns_records/dns_records.py
  dm/templates/dns_records/dns_records.py.schema
  dm/templates/dns_records/tests/integration/dns_records.bats
Labels: DM, cla: yes, feature request

#202 Fixes #186: DM/vpn: refactoring
  dm/templates/vpn/tests/integration/vpn.bats
  dm/templates/vpn/tests/integration/vpn.yaml
  dm/templates/vpn/vpn.py
  dm/templates/vpn/vpn.py.schema
Labels: DM, cla: yes

#207 Fixes #185: DM/stackdriver_metric_descriptor: refactoring
  dm/templates/stackdriver_metric_descriptor/examples/stackdriver_metric_descriptor.yaml
  dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py
  dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py.schema
  dm/templates/stackdriver_metric_descriptor/tests/integration/stackdriver_metric_descriptor.yaml
Labels: DM, cla: yes

#211 Fixes #180: DM/cloudbuild: refactoring
  dm/templates/cloudbuild/cloudbuild.py
  dm/templates/cloudbuild/cloudbuild.py.schema
  dm/templates/cloudbuild/trigger.py
  dm/templates/cloudbuild/trigger.py.schema
Labels: DM, cla: yes

#212 Fixes #179: DM/cloud_tasks: refactoring
  dm/templates/cloud_tasks/queue.py
  dm/templates/cloud_tasks/queue.py.schema
  dm/templates/cloud_tasks/task.py
  dm/templates/cloud_tasks/task.py.schema
Labels: DM, cla: yes

#214 Fixes #145: DM/network_peering: refactoring
  dm/templates/network_peering/network_peering.py
  dm/templates/network_peering/network_peering.py.schema
  dm/templates/network_peering/tests/integration/network_peering.bats
Labels: DM, cla: yes

#215 Refactored shared_vpc_subnet_iam template
  dm/templates/shared_vpc_subnet_iam/README.md
  dm/templates/shared_vpc_subnet_iam/examples/shared_vpc_subnet_iam_bindings.yaml
  dm/templates/shared_vpc_subnet_iam/examples/shared_vpc_subnet_iam_legacy.yaml
  dm/templates/shared_vpc_subnet_iam/examples/shared_vpc_subnet_iam_policy.yaml
  dm/templates/shared_vpc_subnet_iam/shared_vpc_subnet_iam.py
  dm/templates/shared_vpc_subnet_iam/shared_vpc_subnet_iam.py.schema
  dm/templates/shared_vpc_subnet_iam/tests/integration/bindings.bats
  dm/templates/shared_vpc_subnet_iam/tests/integration/bindings.yaml
  dm/templates/shared_vpc_subnet_iam/tests/integration/legacy.bats
  dm/templates/shared_vpc_subnet_iam/tests/integration/legacy.yaml
  dm/templates/shared_vpc_subnet_iam/tests/integration/policy.bats
  dm/templates/shared_vpc_subnet_iam/tests/integration/policy.yaml
  dm/templates/shared_vpc_subnet_iam/tests/integration/shared_vpc_subnet_iam.bats
Labels: DM, cla: yes

#221 Fixes #220: [DM] Backend_service update example according to schema v…
  dm/templates/backend_service/examples/backend_service_regional.yaml
Labels: DM, cla: yes

#224 Update Kubernetes Engine lint to 2.3.0
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
Labels: TF, cla: yes, feature request

#228 Fixes #144: DM/logsink: refactoring
  dm/templates/logsink/logsink.py
  dm/templates/logsink/logsink.py.schema
Labels: DM, cla: yes

#229 Add gems for Kubernetes Engine to Kitchen-Terraform image
  infra/concourse/Makefile.BUILD
  infra/concourse/build/data/Gemfile
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
Labels: TF, cla: yes, feature request

#237 Update Forseti pipelines to 0.12 images
  infra/concourse/pipelines/terraform-google-forseti.yml
Labels: TF, cla: yes, feature request

#244 Update terraform-google-cloud-nat images to Terraform 0.12.x
  infra/concourse/pipelines/terraform-google-cloud-nat.yml
Labels: cla: yes

#210 Add Concourse pipeline for Folders module
  infra/concourse/pipelines/terraform-google-folders.yml
  infra/terraform/test_fixtures/terraform-google-folders.tf
Labels: TF, cla: yes

#223 Add Concourse pipeline for SQL DB and Service Accounts modules
  infra/concourse/pipelines/terraform-google-service-accounts.yml
  infra/concourse/pipelines/terraform-google-sql-db.yml
  infra/terraform/test_fixtures/terraform-google-service-accounts.tf
  infra/terraform/test_fixtures/terraform-google-sql-db.tf
Labels: TF, cla: yes

#240 Update VPN pipeline for Terraform 0.12
  infra/concourse/pipelines/terraform-google-vpn.yml
Labels: TF, cla: yes, feature request

#232 Add Concourse pipeline for IAM module
  infra/concourse/pipelines/terraform-google-iam.yml
  infra/terraform/test_fixtures/outputs.tf
  infra/terraform/test_fixtures/terraform-google-cloud-nat.tf
  infra/terraform/test_fixtures/terraform-google-iam.tf
  infra/terraform/test_fixtures/terraform-google-jenkins.tf
  infra/terraform/test_fixtures/terraform-google-vm.tf
Labels: cla: yes

#241 Enable GKE DM template to support 'latest' initial cluster version.
  dm/templates/gke/gke.py
Labels: cla: yes

#238 Add networkURL tag to firewall DM template.
  dm/templates/firewall/firewall.py
  dm/templates/firewall/firewall.py.schema
Labels: cla: yes

#231 Fixes #146
  dm/templates/org_policy/org_policy.py
  dm/templates/org_policy/org_policy.py.schema
  dm/templates/org_policy/tests/integration/org_policy.bats
Labels: DM, cla: yes

#239 Fixes #181: DM/forseti: refactoring
  dm/templates/forseti/client.py
  dm/templates/forseti/client.py.schema
  dm/templates/forseti/forseti.py
  dm/templates/forseti/forseti.py.schema
  dm/templates/forseti/server.py
  dm/templates/forseti/server.py.schema
Labels: DM, cla: yes

#251 Add support for Terraform 0.12 to Event Function pipeline
  infra/concourse/pipelines/terraform-google-event-function.yml
Labels: cla: yes

#248 Docker image versions updated for tests vm module with terraform-0.12
  infra/concourse/pipelines/terraform-google-vm.yml
Labels: cla: yes, feature request

#253 update module dependancy to make this buildable
  cli/go.mod
  cli/go.sum
Labels: cla: yes

#254 Fixes #180: Add tests for beta submodules/examples
  infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
  infra/terraform/test_fixtures/terraform-google-kubernetes-engine.tf
Labels: cla: yes

#256 Fixes #180: Add tests for beta submodules/examples
  infra/terraform/test_fixtures/terraform-google-kubernetes-engine.tf
Labels: cla: yes

#235 Enable cloud_router DM template to support networkURL.
  dm/templates/cloud_router/cloud_router.py
  dm/templates/cloud_router/cloud_router.py.schema
Labels: DM, cla: yes

#258 Add missing Terraform webhook output keys
  infra/terraform/test_fixtures/outputs.tf
Labels: TF, cla: yes, feature request

#259 Versions of containers fixed
  infra/concourse/pipelines/terraform-google-address.yml
Labels: cla: yes
