Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-08, with the labels that each got.

#762 Install kpt in the devtools image
  infra/build/Makefile
  infra/build/developer-tools/build/install_cloud_sdk.sh
Labels: cla: yes

#764 Addd requirements for cleanup script & new folder
  infra/terraform/test-org/ci-triggers/locals.tf
  infra/terraform/test-org/org/locals.tf
  infra/utils/requirements.txt
Labels: cla: yes

#767 chore(image): Release minor versions of CFT image
  infra/build/Makefile
Labels: cla: yes

#761 [KCC] Adding helm solution for creating PostgreSQL High Availability.
  config-connector/solutions/sql/helm/postgres-ha/Chart.yaml
  config-connector/solutions/sql/helm/postgres-ha/README.md
  config-connector/solutions/sql/helm/postgres-ha/templates/secret.yaml
  config-connector/solutions/sql/helm/postgres-ha/templates/sqldatabase.yaml
  config-connector/solutions/sql/helm/postgres-ha/templates/sqlinstance.yaml
  config-connector/solutions/sql/helm/postgres-ha/templates/sqluser.yaml
  config-connector/solutions/sql/helm/postgres-ha/values.yaml
Labels: KCC, cla: yes

#775 Fix Cloud Build trigger example & template schema
  dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml
  dm/templates/cloudbuild/trigger.py.schema
Labels: DM, bug, cla: yes

#776 Bump_kitchen_terraform_version_to_latest
  infra/build/Makefile
  infra/build/developer-tools/build/data/Gemfile
  infra/build/developer-tools/build/data/Gemfile.lock
Labels: cla: yes

#772 [KCC] Add Helm project-iam solution
  config-connector/solutions/iam/helm/project-iam/Chart.yaml
  config-connector/solutions/iam/helm/project-iam/README.md
  config-connector/solutions/iam/helm/project-iam/templates/iampolicymember.yaml
  config-connector/solutions/iam/helm/project-iam/values.yaml
Labels: KCC, cla: yes
