Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-01, with the labels that each got.

#524 Cloud_router template schema rework
  dm/CHANGELOG.md
  dm/templates/cloud_router/cloud_router.py
  dm/templates/cloud_router/cloud_router.py.schema
  dm/templates/cloud_router/examples/cloud_nat_router.yaml
  dm/templates/cloud_router/tests/integration/cloud_router.bats
  dm/templates/cloud_router/tests/integration/cloud_router.yaml
Labels: cla: yes

#514 Limited ports to use for the TCP external proxy according to docs
  dm/CHANGELOG.md
  dm/templates/external_load_balancer/external_load_balancer.py.schema
Labels: cla: yes

#307 Launchpad folder generation
  cli/cmd/launchpad.go
  cli/go.mod
  cli/go.sum
  cli/launchpad/doc.go
  cli/launchpad/folder.go
  cli/launchpad/folder_test.go
  cli/launchpad/generic.go
  cli/launchpad/org.go
  cli/launchpad/org_test.go
  cli/launchpad/root.go
  cli/launchpad/runtime.go
  cli/launchpad/runtime_test.go
  cli/launchpad/statics.go
  cli/testdata/launchpad/folder/folder_1.yaml
  cli/testdata/launchpad/folder/folder_12.yaml
  cli/testdata/launchpad/folder/org_1.yaml
Labels: TF, cla: yes

#532 Update GKE logging and monitoring API
  dm/templates/gke/tests/integration/gke.bats
Labels: DM, bug, cla: yes

#531 Update gke template to support python3
  dm/CHANGELOG.md
  dm/templates/gke/gke.py
  dm/templates/gke/gke.py.schema
Labels: DM, cla: yes

#534 Update TF to 0.12.19
  infra/build/Makefile
Labels: cla: yes

#537 Launchpad nested folders and conflict definitions
  cli/launchpad/folder.go
  cli/launchpad/folder_test.go
  cli/launchpad/generic.go
  cli/launchpad/org.go
  cli/launchpad/runtime.go
  cli/launchpad/runtime_test.go
  cli/testdata/launchpad/folder/folder_1_nested.yaml
  cli/testdata/launchpad/folder/org_2_nested_conflict.yaml
Labels: cla: yes

#539 Adding support for releaseChannel setting
  dm/CHANGELOG.md
  dm/templates/gke/gke.py
  dm/templates/gke/gke.py.schema
Labels: DM, cla: yes

#543 Varies scorecard bugfixes
  cli/scorecard/cmd.go
  cli/scorecard/score.go
  cli/scorecard/violations.go
Labels: cla: yes

#544 scorecard - Cloud Asset Inventory refresh feature
  cli/docs/scorecard.md
  cli/scorecard/cmd.go
  cli/scorecard/inventory.go
Labels: cla: yes

#548 Update terraform to 0.12.20
  infra/build/Makefile
Labels: cla: yes

#549 Give roles/browser to dev group
  infra/terraform/test-org/org/iam.tf
Labels: cla: yes

#551 Label support for FW rule
  dm/templates/external_load_balancer/external_load_balancer.py
  dm/templates/external_load_balancer/external_load_balancer.py.schema
  dm/templates/external_load_balancer/tests/integration/external_load_balancer.yaml
  dm/templates/forwarding_rule/examples/forwarding_rule_global.yaml
  dm/templates/forwarding_rule/forwarding_rule.py
  dm/templates/forwarding_rule/forwarding_rule.py.schema
  dm/templates/forwarding_rule/tests/integration/forwarding_rule.bats
  dm/templates/forwarding_rule/tests/integration/forwarding_rule.yaml
Labels: DM, cla: yes

#542 Adding sslCertificates support for GCLB
  dm/CHANGELOG.md
  dm/templates/external_load_balancer/external_load_balancer.py
  dm/templates/external_load_balancer/external_load_balancer.py.schema
  dm/templates/external_load_balancer/tests/integration/external_load_balancer.yaml
  dm/templates/healthcheck/healthcheck.py
  dm/templates/healthcheck/healthcheck.py.schema
  dm/templates/healthcheck/tests/integration/healthcheck.bats
  dm/templates/healthcheck/tests/integration/healthcheck.yaml
  dm/templates/target_proxy/target_proxy.py
  dm/templates/target_proxy/target_proxy.py.schema
  dm/templates/target_proxy/tests/integration/target_proxy.bats
  dm/templates/target_proxy/tests/integration/target_proxy.yaml
Labels: DM, cla: yes

#538 [DM] Fix intermittent cloud sql template python3 warning
  dm/CHANGELOG.md
  dm/templates/cloud_sql/cloud_sql.py
  dm/templates/cloud_sql/cloud_sql.py.schema
Labels: cla: yes

#552 Fixing forwardingRule label support
  dm/templates/external_load_balancer/tests/integration/external_load_balancer.yaml
  dm/templates/forwarding_rule/forwarding_rule.py
  dm/templates/forwarding_rule/tests/integration/forwarding_rule.yaml
Labels: DM, bug, cla: yes

#528 Autogen modules helper
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/generate_modules.py
Labels: cla: yes
