Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-04, with the labels that each got.

#632 Removing hard coded string `-1` in install_bats.sh
  infra/build/developer-tools/build/install_bats.sh
Labels: cla: yes

#610 Add Config Connector solution service-account
  config-connector/solutions/iam/kpt/service-account/Kptfile
  config-connector/solutions/iam/kpt/service-account/README.md
  config-connector/solutions/iam/kpt/service-account/iampolicymember.yaml
  config-connector/solutions/iam/kpt/service-account/iamserviceaccount.yaml
Labels: KCC, cla: yes

#634 Increment version number
  cli/Makefile
Labels: cla: yes

#613 Scorecard - handle changes from new Config Validator version w.r.t. Violation format and k8s resource handling
  cli/go.mod
  cli/go.sum
  cli/scorecard/main.go
  cli/scorecard/proto_test.go
  cli/scorecard/score.go
  cli/scorecard/violations.go
  cli/scorecard/violations_test.go
  cli/testdata/scorecard/cai-dir/iam_inventory.json
  cli/testdata/scorecard/cai-dir/resource_inventory.json
  cli/testdata/scorecard/policy-library/policies/constraints/k8s_dump_review.yaml
  cli/testdata/scorecard/policy-library/policies/templates/k8s_dump_review_template.yaml
Labels: cla: yes

#626 Added composer to modules
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#622 github workflow for bumping TF/gcloud versions and build/push new image
  .github/workflows/build-push-cft-devtools.yml
  .github/workflows/update-tooling.yml
Labels: TF, cla: yes

#636 Install terragrunt in cft/developer-tools image.
  infra/build/Makefile
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/install_terragrunt.sh
Labels: cla: yes

#638 Add config for SA to push images to GCR
  infra/terraform/test-org/ci-project/backend.tf
  infra/terraform/test-org/ci-project/github.tf
  infra/terraform/test-org/ci-project/locals.tf
  infra/terraform/test-org/ci-project/main.tf
  infra/terraform/test-org/ci-project/outputs.tf
  infra/terraform/test-org/ci-project/sa.tf
Labels: cla: yes

#609 Add ci linting for terraform-example-foundation
  infra/terraform/test-org/ci-triggers/triggers.tf
Labels: TF, cla: yes

#640 Upgrade Terraform version.
  infra/build/Makefile
Labels: cla: yes

#641 Restrict building new dev tools images only when pushed to master
  .github/workflows/build-push-cft-devtools.yml
Labels: cla: yes

#605 Add Config Connector solution member-iam
  config-connector/solutions/iam/README.md
  config-connector/solutions/iam/kpt/README.md
  config-connector/solutions/iam/kpt/member-iam/0-namespace.yaml
  config-connector/solutions/iam/kpt/member-iam/Kptfile
  config-connector/solutions/iam/kpt/member-iam/README.md
  config-connector/solutions/iam/kpt/member-iam/iampolicymember.yaml
  config-connector/solutions/iam/kpt/member-iam/iamserviceaccount.yaml
Labels: KCC, cla: yes

#612 KCC Solution for IAM policy of PubSub topic
  config-connector/solutions/iam/kpt/pubsub-topic/Kptfile
  config-connector/solutions/iam/kpt/pubsub-topic/README.md
  config-connector/solutions/iam/kpt/pubsub-topic/iampolicymember.yaml
  config-connector/solutions/iam/kpt/pubsub-topic/pubsubtopic.yaml
Labels: KCC, cla: yes

#646 Add Github Actions self hosted Runners to modules
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#625 Implemented project-iam solution
  config-connector/solutions/iam/kpt/project-iam/Kptfile
  config-connector/solutions/iam/kpt/project-iam/README.md
  config-connector/solutions/iam/kpt/project-iam/iampolicymember.yaml
Labels: KCC, cla: yes

#619 implemented iam/pubsub-subscription KCC solution
  config-connector/solutions/iam/kpt/pubsub-subscription/Kptfile
  config-connector/solutions/iam/kpt/pubsub-subscription/README.md
  config-connector/solutions/iam/kpt/pubsub-subscription/iampolicymember.yaml
  config-connector/solutions/iam/kpt/pubsub-subscription/pubsubsubscription.yaml
  config-connector/solutions/iam/kpt/pubsub-subscription/pubsubtopic.yaml
Labels: KCC, cla: yes

#618 Add owned-project Solution
  config-connector/solutions/projects/kpt/owned-project/Kptfile
  config-connector/solutions/projects/kpt/owned-project/README.md
  config-connector/solutions/projects/kpt/owned-project/iampolicymember.yaml
  config-connector/solutions/projects/kpt/owned-project/project.yaml
Labels: KCC, cla: yes

#647 Switch to using cloud-foundation-bot to open PRs
  .github/workflows/update-tooling.yml
Labels: cla: yes

#617 Implemented storage-bucket-iam KCC Solution
  config-connector/solutions/iam/kpt/storage-bucket-iam/Kptfile
  config-connector/solutions/iam/kpt/storage-bucket-iam/README.md
  config-connector/solutions/iam/kpt/storage-bucket-iam/iampolicymember.yaml
Labels: KCC, cla: yes

#621 Implement KCC solution for folder-iam
  config-connector/solutions/iam/kpt/folder-iam/Kptfile
  config-connector/solutions/iam/kpt/folder-iam/README.md
  config-connector/solutions/iam/kpt/folder-iam/iampolicymember.yaml
Labels: KCC, cla: yes

#649 Remove myself from reviewer list for action PRs
  .github/workflows/update-tooling.yml
Labels: cla: yes

#616 Update unmanaged_instance_group.py
  dm/CHANGELOG.md
  dm/templates/unmanaged_instance_group/unmanaged_instance_group.py
Labels: cla: yes

#629 Adding Config Connector wordpress solution under apps area
  config-connector/solutions/README.md
  config-connector/solutions/apps/helm/wordpress/README.md
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/.helmignore
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/Chart.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-sql-api.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-sql-db.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-sql-instance.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-sql-policy-member.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-sql-service-account.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-sql-user.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/gcp-wi-policy.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/k8s-external-load-balancer.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/k8s-service-account.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/k8s-sql-db-credentials.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/templates/k8s-stateful-set.yaml
  config-connector/solutions/apps/helm/wordpress/charts/wordpress-gcp/values.yaml
  config-connector/solutions/projects/kpt/README.md
Labels: KCC, cla: yes

#623 Iam/kms key ring solution
  config-connector/solutions/iam/kpt/kms-key-ring/Kptfile
  config-connector/solutions/iam/kpt/kms-key-ring/README.md
  config-connector/solutions/iam/kpt/kms-key-ring/iampolicymember.yaml
  config-connector/solutions/iam/kpt/kms-key-ring/kmskeyring.yaml
Labels: KCC, cla: yes

#650 Add release-please label to all repos
  infra/terraform/test-org/github/main.tf
Labels: cla: yes

#645 Implement KCC subnet solution
  config-connector/solutions/iam/kpt/subnet/Kptfile
  config-connector/solutions/iam/kpt/subnet/README.md
  config-connector/solutions/iam/kpt/subnet/computenetwork.yaml
  config-connector/solutions/iam/kpt/subnet/iampolicymember.yaml
  config-connector/solutions/iam/kpt/subnet/subnet.yaml
Labels: KCC, cla: yes

#635 Mysql private solution
  config-connector/solutions/sql/kpt/mysql-private/Kptfile
  config-connector/solutions/sql/kpt/mysql-private/README.md
  config-connector/solutions/sql/kpt/mysql-private/network/computeaddress.yaml
  config-connector/solutions/sql/kpt/mysql-private/network/computenetwork.yaml
  config-connector/solutions/sql/kpt/mysql-private/network/servicenetworkingconnection.yaml
  config-connector/solutions/sql/kpt/mysql-private/sql/secret.yaml
  config-connector/solutions/sql/kpt/mysql-private/sql/sqldatabase.yaml
  config-connector/solutions/sql/kpt/mysql-private/sql/sqlinstance.yaml
  config-connector/solutions/sql/kpt/mysql-private/sql/sqluser.yaml
Labels: KCC, cla: yes

#631 implemented postgres-ha solution
  config-connector/solutions/sql/kpt/postgres-ha/Kptfile
  config-connector/solutions/sql/kpt/postgres-ha/README.md
  config-connector/solutions/sql/kpt/postgres-ha/secret.yaml
  config-connector/solutions/sql/kpt/postgres-ha/sqldatabase.yaml
  config-connector/solutions/sql/kpt/postgres-ha/sqlinstance.yaml
  config-connector/solutions/sql/kpt/postgres-ha/sqluser.yaml
Labels: KCC, cla: yes

#643 Shared VPC solution
  config-connector/solutions/projects/kpt/shared-vpc/0-namespace.yaml
  config-connector/solutions/projects/kpt/shared-vpc/Kptfile
  config-connector/solutions/projects/kpt/shared-vpc/README.md
  config-connector/solutions/projects/kpt/shared-vpc/network.yaml
  config-connector/solutions/projects/kpt/shared-vpc/project.yaml
  config-connector/solutions/projects/kpt/shared-vpc/service.yaml
  config-connector/solutions/projects/kpt/shared-vpc/sharedvpchostproject.yaml
  config-connector/solutions/projects/kpt/shared-vpc/sharedvpcserviceproject.yaml
Labels: KCC, cla: yes

#624 implemented iam/kms-crypto-key solution
  config-connector/solutions/iam/kpt/kms-crypto-key/Kptfile
  config-connector/solutions/iam/kpt/kms-crypto-key/README.md
  config-connector/solutions/iam/kpt/kms-crypto-key/iampolicymember.yaml
  config-connector/solutions/iam/kpt/kms-crypto-key/kmscryptokey.yaml
  config-connector/solutions/iam/kpt/kms-crypto-key/kmskeyring.yaml
Labels: KCC, cla: yes

#653 Add the API requirement for member-iam and project-iam solutions
  config-connector/solutions/iam/kpt/member-iam/README.md
  config-connector/solutions/iam/kpt/project-iam/README.md
Labels: KCC, cla: yes

#656 [KCC] Remove the dependency on Go for test-cli users
  config-connector/tests/README.md
Labels: cla: yes

#630 added mysql-ha solution
  config-connector/solutions/sql/kpt/mysql-ha/Kptfile
  config-connector/solutions/sql/kpt/mysql-ha/README.md
  config-connector/solutions/sql/kpt/mysql-ha/secret.yaml
  config-connector/solutions/sql/kpt/mysql-ha/sqldatabase.yaml
  config-connector/solutions/sql/kpt/mysql-ha/sqlinstance.yaml
  config-connector/solutions/sql/kpt/mysql-ha/sqluser.yaml
Labels: KCC, cla: yes

#655 [KCC] Helm solution for service account
  config-connector/solutions/iam/helm/service-account/Chart.yaml
  config-connector/solutions/iam/helm/service-account/README.md
  config-connector/solutions/iam/helm/service-account/templates/iampolicymember.yaml
  config-connector/solutions/iam/helm/service-account/templates/iamserviceaccount.yaml
  config-connector/solutions/iam/helm/service-account/values.yaml
Labels: KCC, cla: yes

#661 mySQL public solution
  config-connector/solutions/sql/kpt/mysql-public/Kptfile
  config-connector/solutions/sql/kpt/mysql-public/README.md
  config-connector/solutions/sql/kpt/mysql-public/secret.yaml
  config-connector/solutions/sql/kpt/mysql-public/sqldatabase.yaml
  config-connector/solutions/sql/kpt/mysql-public/sqlinstance.yaml
  config-connector/solutions/sql/kpt/mysql-public/sqluser.yaml
Labels: KCC, cla: yes
