Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-10, with the labels that each got.

#803 fix: add python3 headers for dev tools image
  infra/build/developer-tools/build/install_dependencies.sh
Labels: cla: yes

#805 Fix policy constraint path in Scorecard tutorial
  cli/docs/scorecard.md
Labels: cla: yes

#782 Dev project cleaner for cft-dev org
  infra/terraform/dev-org/dev-project-cleanup/backend.tf
  infra/terraform/dev-org/dev-project-cleanup/cleanup.tf
  infra/terraform/dev-org/dev-project-cleanup/locals.tf
  infra/terraform/dev-org/dev-project-cleanup/outputs.tf
  infra/terraform/dev-org/dev-project-cleanup/project.tf
  infra/terraform/dev-org/dev-project-cleanup/versions.tf
Labels: cla: yes

#804 [DM] Add gke AutoscalingProfile to schema
  dm/templates/gke/gke.py.schema
Labels: DM, cla: yes

#811 Update go version to 1.15
  infra/build/Makefile
Labels: cla: yes

#791 Add new labels for terraform-google-modules
  infra/terraform/test-org/github/main.tf
Labels: TF, cla: yes

#817 Update to kitchen-terraform 5.5 for Terraform 13
  infra/build/Makefile
  infra/build/developer-tools/build/data/Gemfile
  infra/build/developer-tools/build/data/Gemfile.lock
Labels: cla: yes

#815 feat: refactor Terraform docs script
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_docs.sh
Labels: cla: yes

#808 feat: Add int tests for training
  infra/terraform/test-org/ci-triggers/locals.tf
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#778 add_the_cloud_router_module_to_the_tests
  infra/terraform/test-org/org/locals.tf
Labels: cla: yes

#806 Fixing duplicate entry at DNS Managed zones schema
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
Labels: DM, bug, cla: yes

#773 feat: Add tf-bundle, parallel validate for cft-tools
  infra/build/Makefile
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#822 Updated cloud_sql.py.schema to allow new versions
  dm/templates/cloud_sql/cloud_sql.py.schema
Labels: DM, cla: yes

#796 Update project.py.schema
  dm/templates/project/project.py.schema
Labels: DM, cla: yes
