Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-05, with the labels that each got.

#660 [KCC] postgreSQL public solution
  config-connector/solutions/sql/kpt/postgres-public/Kptfile
  config-connector/solutions/sql/kpt/postgres-public/README.md
  config-connector/solutions/sql/kpt/postgres-public/secret.yaml
  config-connector/solutions/sql/kpt/postgres-public/sqldatabase.yaml
  config-connector/solutions/sql/kpt/postgres-public/sqlinstance.yaml
  config-connector/solutions/sql/kpt/postgres-public/sqluser.yaml
Labels: KCC, cla: yes

#668 [KCC] Add explanation about the solutions that can't be tested via test-cli
  config-connector/tests/README.md
Labels: KCC, cla: yes

#667 [KCC] Print out resource status if they are not ready after the timeout
  config-connector/tests/ccs-test/cmd/root.go
Labels: KCC, cla: yes

#674 [KCC] Solutions Helm README edit
  config-connector/solutions/README.md
Labels: KCC, cla: yes

#669 [KCC] Update Config Connector solutions doc
  config-connector/solutions/README.md
  config-connector/solutions/iam/README.md
  config-connector/solutions/sql/kpt/mysql-public/Kptfile
  config-connector/solutions/sql/kpt/mysql-public/README.md
  config-connector/solutions/sql/kpt/postgres-public/Kptfile
  config-connector/solutions/sql/kpt/postgres-public/README.md
  config-connector/tests/README.md
Labels: KCC, cla: yes

#665 [KCC] Implement folder-iam helm solution
  config-connector/solutions/iam/helm/folder-iam/Chart.yaml
  config-connector/solutions/iam/helm/folder-iam/README.md
  config-connector/solutions/iam/helm/folder-iam/templates/iampolicymember.yaml
  config-connector/solutions/iam/helm/folder-iam/values.yaml
Labels: KCC, cla: yes

#677 Scorecard new feature - Support Org Policy, Access Policy asset types with new Config Validator version
  cli/docs/scorecard.md
  cli/go.mod
  cli/go.sum
  cli/scorecard/inventory.go
  cli/scorecard/proto.go
  cli/scorecard/violations.go
  cli/scorecard/violations_test.go
  cli/testdata/scorecard/cai-dir/access_policy_inventory.json
  cli/testdata/scorecard/cai-dir/org_policy_inventory.json
  cli/testdata/scorecard/policy-library/lib/.gitignore
  cli/testdata/scorecard/policy-library/lib/constraints.rego
  cli/testdata/scorecard/policy-library/lib/util.rego
  cli/testdata/scorecard/policy-library/policies/constraints/k8s_pod_image_pull_policy.yaml
  cli/testdata/scorecard/policy-library/policies/constraints/org_policy_skip_default_network.yaml
  cli/testdata/scorecard/policy-library/policies/constraints/vpc_sc_ensure_services.yaml
  cli/testdata/scorecard/policy-library/policies/templates/gcp_org_policy_skip_default_network.yaml
  cli/testdata/scorecard/policy-library/policies/templates/gcp_vpc_sc_ensure_services_v1.yaml
  cli/testdata/scorecard/policy-library/policies/templates/k8s_dump_review_template.yaml
  cli/testdata/scorecard/policy-library/policies/templates/k8s_image_pull_policy.yaml
Labels: cla: yes

#673 [KCC] Add the test case for project-services solution
  config-connector/tests/testcases/projects/kpt/project-services/original_values.yaml
  config-connector/tests/testcases/projects/kpt/project-services/required_fields_only.yaml
Labels: KCC, cla: yes

#679 [KCC] Fix the README of service-account helm solution
  config-connector/solutions/iam/helm/service-account/README.md
Labels: KCC, cla: yes

#684 Add markdown output for CFT linter action
  infra/build/Makefile
  infra/build/developer-tools/build/scripts/test_lint.sh
Labels: cla: yes

#683 [KCC] Add test cases for project-iam, pubsub-subscription and pubsub-topic …
  config-connector/solutions/iam/kpt/pubsub-subscription/Kptfile
  config-connector/solutions/iam/kpt/pubsub-subscription/README.md
  config-connector/solutions/iam/kpt/pubsub-topic/README.md
  config-connector/tests/testcases/iam/kpt/project-iam/original_values.yaml
  config-connector/tests/testcases/iam/kpt/project-iam/required_fields_only.yaml
  config-connector/tests/testcases/iam/kpt/pubsub-subscription/original_values.yaml
  config-connector/tests/testcases/iam/kpt/pubsub-subscription/required_fields_only.yaml
  config-connector/tests/testcases/iam/kpt/pubsub-topic/original_values.yaml
  config-connector/tests/testcases/iam/kpt/pubsub-topic/required_fields_only.yaml
Labels: KCC, cla: yes

#678 [KCC] Implement a KCC helm solution for subnet
  config-connector/solutions/iam/helm/subnet/Chart.yaml
  config-connector/solutions/iam/helm/subnet/README.md
  config-connector/solutions/iam/helm/subnet/templates/computernetwork.yaml
  config-connector/solutions/iam/helm/subnet/templates/iampolicymember.yaml
  config-connector/solutions/iam/helm/subnet/templates/subnet.yaml
  config-connector/solutions/iam/helm/subnet/values.yaml
Labels: KCC, cla: yes

#685 Cloud Functions IAM member example
  dm/templates/iam_member/examples/iam_member_resource.yaml
Labels: DM, cla: yes

#680 Fixed non-working external reference in IAMPolicyMember
  config-connector/solutions/iam/kpt/storage-bucket-iam/Kptfile
  config-connector/solutions/iam/kpt/storage-bucket-iam/iampolicymember.yaml
Labels: KCC, cla: yes

#687 Add script to autogenerate Terraform module docs.
  docs/meta/generate-index.py
  docs/meta/index.yaml
  docs/meta/requirements.txt
  docs/meta/terraform.md.tmpl
  docs/terraform.md
Labels: cla: yes

#689 CLI - Increment version number
  cli/Makefile
Labels: cla: yes

#690 Add GitHub action for releasing CLI.
  .github/workflows/build-push-cft-devtools.yml
  .github/workflows/release-cli.yml
  cli/Makefile
  cli/cmd/version.go
Labels: cla: yes

#637 Added setters table for project-services
  config-connector/solutions/projects/kpt/project-services/README.md
Labels: KCC, cla: yes

#692 [KCC] Fix nits in the READMEs
  config-connector/solutions/iam/helm/folder-iam/README.md
  config-connector/solutions/iam/kpt/folder-iam/README.md
  config-connector/solutions/iam/kpt/member-iam/README.md
  config-connector/solutions/iam/kpt/service-account/README.md
  config-connector/solutions/projects/kpt/owned-project/README.md
  config-connector/solutions/projects/kpt/project-hierarchy/README.md
  config-connector/solutions/projects/kpt/project-services/README.md
  config-connector/solutions/projects/kpt/shared-vpc/README.md
  config-connector/solutions/projects/kpt/simple-project/README.md
  config-connector/tests/README.md
Labels: KCC, cla: yes

#698 Add kustomize to CFT developer tools
  infra/build/Makefile
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/install_kustomize.sh
Labels: cla: yes

#694 Adds script to comment on PR, helper func for invocation within Cloud Build
  infra/build/Makefile
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/data/requirements.txt
  infra/build/developer-tools/build/scripts/gh_lint_comment.py
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
Labels: cla: yes

#696 [KCC] Add test cases for all the SQL solutions
  config-connector/solutions/iam/kpt/README.md
  config-connector/solutions/sql/kpt/mysql-ha/README.md
  config-connector/solutions/sql/kpt/mysql-private/README.md
  config-connector/solutions/sql/kpt/mysql-public/README.md
  config-connector/solutions/sql/kpt/postgres-ha/README.md
  config-connector/solutions/sql/kpt/postgres-public/Kptfile
  config-connector/solutions/sql/kpt/postgres-public/README.md
  config-connector/tests/README.md
  config-connector/tests/ccs-test/cmd/root.go
  config-connector/tests/testcases/environments.template
  config-connector/tests/testcases/sql/kpt/mysql-ha/original_values.yaml
  config-connector/tests/testcases/sql/kpt/mysql-ha/required_fields_with_sql_instance_name.yaml
  config-connector/tests/testcases/sql/kpt/mysql-public/original_values.yaml
  config-connector/tests/testcases/sql/kpt/mysql-public/required_fields_with_sql_instance_name.yaml
  config-connector/tests/testcases/sql/kpt/postgres-ha/original_values.yaml
  config-connector/tests/testcases/sql/kpt/postgres-ha/required_fields_with_sql_instance_name.yaml
  config-connector/tests/testcases/sql/kpt/postgres-public/original_values.yaml
  config-connector/tests/testcases/sql/kpt/postgres-public/required_fields_with_sql_instance_name.yaml
Labels: KCC, cla: yes

#701 Fix output test cases broken in #690
  cli/Makefile
  cli/cmd/root.go
  cli/cmd/root_test.go
  cli/cmd/version.go
Labels: cla: yes

#699 [KCC] Add the option to run all the tests in one command
  config-connector/tests/README.md
  config-connector/tests/ccs-test/cmd/root.go
  config-connector/tests/testcases/environments.template
  config-connector/tests/testcases/projects/kpt/owned-project/required_fields_only.yaml
  config-connector/tests/testcases/projects/kpt/simple-project/required_fields_only.yaml
Labels: KCC, cla: yes

#695 [KCC] Support Helm PubSub-topic solution
  config-connector/solutions/iam/helm/pubsub-topic/Chart.yaml
  config-connector/solutions/iam/helm/pubsub-topic/README.md
  config-connector/solutions/iam/helm/pubsub-topic/templates/iampolicymember.yaml
  config-connector/solutions/iam/helm/pubsub-topic/templates/pubsubtopic.yaml
  config-connector/solutions/iam/helm/pubsub-topic/values.yaml
Labels: KCC, cla: yes
