Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-02, with the labels that each got.

#547 scorecard - new feature to include additional metadata fields in output
  cli/docs/scorecard.md
  cli/scorecard/cmd.go
  cli/scorecard/score.go
Labels: cla: yes

#556 scorecard - enhancement to handle output metadata of all types
  cli/scorecard/cmd.go
  cli/scorecard/proto.go
  cli/scorecard/score.go
Labels: cla: yes

#559 Removing Schema self reference imports
  dm/templates/bastion/README.md
  dm/templates/bigquery/bigquery_dataset.py.schema
  dm/templates/bigquery/bigquery_table.py.schema
  dm/templates/cloud_filestore/cloud_filestore.py.schema
  dm/templates/cloud_router/cloud_router.py.schema
  dm/templates/cloud_sql/cloud_sql.py.schema
  dm/templates/cloud_tasks/queue.py.schema
  dm/templates/cloud_tasks/task.py.schema
  dm/templates/cloudbuild/cloudbuild.py.schema
  dm/templates/cloudbuild/trigger.py.schema
  dm/templates/dataproc/dataproc.py.schema
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
  dm/templates/dns_records/dns_records.py.schema
  dm/templates/folder/folder.py.schema
  dm/templates/gcs_bucket/gcs_bucket.py.schema
  dm/templates/gke/gke.py.schema
  dm/templates/haproxy/haproxy.py.schema
  dm/templates/healthcheck/healthcheck.py.schema
  dm/templates/iam_custom_role/organization_custom_role.py.schema
  dm/templates/iam_custom_role/project_custom_role.py.schema
  dm/templates/iam_member/iam_member.py.schema
  dm/templates/instance/instance.py.schema
  dm/templates/interconnect/interconnect.py.schema
  dm/templates/interconnect_attachment/interconnect_attachment.py.schema
  dm/templates/kms/kms.py.schema
  dm/templates/network/network.py.schema
  dm/templates/network_peering/network_peering.py.schema
  dm/templates/org_policy/org_policy.py.schema
  dm/templates/resource_policy/resource_policy.py.schema
  dm/templates/route/route.py.schema
  dm/templates/route/single_route.py.schema
  dm/templates/shared_vpc_subnet_iam/shared_vpc_subnet_iam.py.schema
  dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py.schema
  dm/templates/stackdriver_notification_channels/stackdriver_notification_channels.py.schema
Labels: DM, cla: yes

#560 Added serviceAccountEmailAddress to output fields
  dm/templates/cloud_sql/cloud_sql.py
Labels: DM, cla: yes

#561 CloudSQL - Same user with different host
  dm/templates/cloud_sql/cloud_sql.py
Labels: DM, cla: yes

#564 Added billing iam test account ID to Cloud Build config
  infra/terraform/test-org/ci-triggers/locals.tf
  infra/terraform/test-org/ci-triggers/triggers.tf
Labels: cla: yes

#566 Updated test_billing_account only for billing-iam
  infra/terraform/test-org/ci-triggers/triggers.tf
Labels: cla: yes

#567 Update module name to google-iam for iam trigger
  infra/terraform/test-org/ci-triggers/triggers.tf
Labels: cla: yes

#568 Fixed module variable error to each.key
  infra/terraform/test-org/ci-triggers/triggers.tf
Labels: cla: yes

#570 Fixing healthcheck specific parameters
  dm/templates/healthcheck/healthcheck.py
  dm/templates/healthcheck/tests/integration/healthcheck.bats
  dm/templates/healthcheck/tests/integration/healthcheck.yaml
Labels: DM, bug, cla: yes

#571 Increasing max number of subdomains
  dm/templates/dns_records/dns_records.py.schema
Labels: DM, cla: yes

#573 DB and user name collision
  dm/CHANGELOG.md
  dm/templates/cloud_sql/cloud_sql.py
  dm/templates/cloud_sql/cloud_sql.py.schema
Labels: cla: yes

#577 Update config validator dependency and fix incompatible changes.
  cli/go.mod
  cli/go.sum
  cli/scorecard/score.go
  cli/scorecard/violations.go
  cli/validation/forseti.go
Labels: cla: yes

#580 Ocsig patch 8 gclb
  dm/templates/external_load_balancer/external_load_balancer.py
  dm/templates/external_load_balancer/external_load_balancer.py.schema
Labels: DM, bug, cla: yes

#583 Update Terraform to 0.12.21
  infra/build/Makefile
Labels: cla: yes

#575 Scorecard - get real asset ancestry path
  cli/go.sum
  cli/scorecard/proto.go
  cli/scorecard/score.go
  cli/scorecard/violations.go
Labels: cla: yes

#585 Remove legacy Terraform configuration
  infra/terraform/applications/cert_manager.tf
  infra/terraform/applications/concourse.tf
  infra/terraform/applications/helm.tf
  infra/terraform/applications/main.tf
  infra/terraform/applications/variables.tf
  infra/terraform/gke/main.tf
  infra/terraform/gke/outputs.tf
  infra/terraform/gke/variables.tf
  infra/terraform/gsuite_groups/README.md
  infra/terraform/gsuite_groups/main.tf
  infra/terraform/gsuite_groups/outputs.tf
  infra/terraform/gsuite_groups/variables.tf
  infra/terraform/modules/variables/main.tf
  infra/terraform/modules/variables/outputs.tf
  infra/terraform/networking/main.tf
  infra/terraform/networking/outputs.tf
  infra/terraform/networking/variables.tf
  infra/terraform/postgres/main.tf
  infra/terraform/postgres/networking.tf
  infra/terraform/postgres/outputs.tf
  infra/terraform/postgres/variables.tf
  infra/terraform/seed_projects/main.tf
  infra/terraform/seed_projects/seymourd.tf
  infra/terraform/seed_projects/variables.tf
  infra/terraform/terraform_backend/main.tf
  infra/terraform/terraform_backend/phoogle.tf
  infra/terraform/terraform_backend/terraform.tfstate
  infra/terraform/terraform_backend/variables.tf
  infra/terraform/test_fixtures/main.tf
  infra/terraform/test_fixtures/outputs.tf
  infra/terraform/test_fixtures/terraform-google-address.tf
  infra/terraform/test_fixtures/terraform-google-cloud-nat.tf
  infra/terraform/test_fixtures/terraform-google-container-vm.tf
  infra/terraform/test_fixtures/terraform-google-event-function.tf
  infra/terraform/test_fixtures/terraform-google-folders.tf
  infra/terraform/test_fixtures/terraform-google-forseti.tf
  infra/terraform/test_fixtures/terraform-google-iam.tf
  infra/terraform/test_fixtures/terraform-google-jenkins.tf
  infra/terraform/test_fixtures/terraform-google-kubernetes-engine.tf
  infra/terraform/test_fixtures/terraform-google-log-export.tf
  infra/terraform/test_fixtures/terraform-google-project-factory.tf
  infra/terraform/test_fixtures/terraform-google-service-accounts.tf
  infra/terraform/test_fixtures/terraform-google-sql-db.tf
  infra/terraform/test_fixtures/terraform-google-startup-scripts.tf
  infra/terraform/test_fixtures/terraform-google-vm.tf
  infra/terraform/test_fixtures/terraform-google-vpn.tf
  infra/terraform/test_fixtures/variables.tf
  infra/utils/delete-projects.py
Labels: cla: yes

#574 Add helper for testing Terraform module generation
  infra/build/Makefile
  infra/build/developer-tools/build/data/requirements.txt
  infra/build/developer-tools/build/scripts/task_helper_functions.sh
  infra/build/developer-tools/build/scripts/test_lint.sh
Labels: cla: yes

#592 Make Go version configurable and upgrade to 1.13
  infra/build/Makefile
  infra/build/developer-tools/Dockerfile
  infra/build/developer-tools/build/install_dependencies.sh
Labels: cla: yes

#588 Scorecard - add some tests
  cli/go.sum
  cli/scorecard/proto_test.go
  cli/scorecard/violations.go
  cli/scorecard/violations_test.go
  cli/testdata/scorecard/cai-dir/iam_inventory.json
  cli/testdata/scorecard/cai-dir/resource_inventory.json
  cli/testdata/scorecard/policy-library/lib/.gitignore
  cli/testdata/scorecard/policy-library/policies/constraints/storage_blacklist_public.yaml
  cli/testdata/scorecard/policy-library/policies/templates/gcp_storage_bucket_world_readable_v1.yaml
  cli/testdata/scorecard/shared/iam_policy.json
  cli/testdata/scorecard/shared/iam_policy_audit_logs.json
  cli/testdata/scorecard/shared/resource.json
Labels: cla: yes

#587 Source representation instance support
  dm/templates/cloud_sql/cloud_sql.py
  dm/templates/cloud_sql/cloud_sql.py.schema
Labels: DM, cla: yes
