Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2020-03, with the labels that each got.

#601 Fixing bucket name issue
  dm/CHANGELOG.md
  dm/templates/project/project.py
  dm/templates/project/project.py.schema
Labels: DM, bug, cla: yes

#591 Cloud Function support for iam_member template
  dm/CHANGELOG.md
  dm/templates/iam_member/README.md
  dm/templates/iam_member/iam_member.py
  dm/templates/iam_member/iam_member.py.schema
  dm/templates/iam_member/tests/integration/iam_member.bats
  dm/templates/iam_member/tests/integration/iam_member.yaml
Labels: DM, cla: yes

#594 GKE schema fixes
  dm/templates/gke/gke.py.schema
Labels: DM, cla: yes

#555 Remove 'latest' default from initialClusterVersion
  dm/templates/gke/gke.py.schema
Labels: DM, cla: yes

#604 Revert changes from #559 and import the subnetwork.py template
  dm/templates/network/network.py.schema
Labels: cla: yes

#608 Cloud Function upload python 3 compatibility
  dm/templates/cloud_function/upload.py
Labels: DM, bug, cla: yes

#598 Add Config Connector Solutions + project-hierarchy
  README.md
  config-connector/solutions/README.md
  config-connector/solutions/projects/kpt/README.md
  config-connector/solutions/projects/kpt/project-hierarchy/Kptfile
  config-connector/solutions/projects/kpt/project-hierarchy/README.md
  config-connector/solutions/projects/kpt/project-hierarchy/folder.yaml
  config-connector/solutions/projects/kpt/project-hierarchy/project.yaml
Labels: cla: yes

#614 Remove enum from initializeParams diskType
  dm/templates/instance/instance.py.schema
Labels: DM, bug, cla: yes

#606 [KCC] ConfigConnector solution for project-services
  config-connector/solutions/projects/kpt/project-services/0-namespace.yaml
  config-connector/solutions/projects/kpt/project-services/Kptfile
  config-connector/solutions/projects/kpt/project-services/README.md
  config-connector/solutions/projects/kpt/project-services/service.yaml
Labels: KCC, cla: yes

#615 Add roles for KCC team to CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#599 Simple project (KCC Solution)
  config-connector/solutions/projects/kpt/simple-project/Kptfile
  config-connector/solutions/projects/kpt/simple-project/README.md
  config-connector/solutions/projects/kpt/simple-project/project.yaml
Labels: KCC, cla: yes
