Repository GoogleCloudPlatform/cloud-foundation-toolkit, pull requests merged in 2021-02, with the labels that each got.

#868 fix: disable comment bot on example foundation
  infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py
Labels: cla: yes

#871 Fixing the `outputs` section in the schema files
  dm/templates/autoscaler/autoscaler.py.schema
  dm/templates/backend_service/backend_service.py.schema
  dm/templates/bastion/bastion.py.schema
  dm/templates/bigquery/bigquery_dataset.py.schema
  dm/templates/bigquery/bigquery_table.py.schema
  dm/templates/cloud_filestore/cloud_filestore.py.schema
  dm/templates/cloud_function/cloud_function.py.schema
  dm/templates/cloud_router/cloud_router.py.schema
  dm/templates/cloud_spanner/cloud_spanner.py.schema
  dm/templates/cloud_sql/cloud_sql.py.schema
  dm/templates/cloud_tasks/queue.py.schema
  dm/templates/cloud_tasks/task.py.schema
  dm/templates/cloudbuild/cloudbuild.py.schema
  dm/templates/dataproc/dataproc.py.schema
  dm/templates/dns_managed_zone/dns_managed_zone.py.schema
  dm/templates/external_load_balancer/external_load_balancer.py.schema
  dm/templates/firewall/firewall.py.schema
  dm/templates/folder/folder.py.schema
  dm/templates/forwarding_rule/forwarding_rule.py.schema
  dm/templates/gcs_bucket/gcs_bucket.py.schema
  dm/templates/gke/gke.py.schema
  dm/templates/haproxy/haproxy.py.schema
  dm/templates/healthcheck/healthcheck.py.schema
  dm/templates/instance/instance.py.schema
  dm/templates/instance_template/instance_template.py.schema
  dm/templates/interconnect/interconnect.py.schema
  dm/templates/interconnect_attachment/interconnect_attachment.py.schema
  dm/templates/internal_load_balancer/internal_load_balancer.py.schema
  dm/templates/ip_reservation/ip_address.py.schema
  dm/templates/ip_reservation/ip_reservation.py.schema
  dm/templates/kms/kms.py.schema
  dm/templates/managed_instance_group/managed_instance_group.py.schema
  dm/templates/nat_gateway/nat_gateway.py.schema
  dm/templates/network/network.py.schema
  dm/templates/network/subnetwork.py.schema
  dm/templates/project/project.py.schema
  dm/templates/pubsub/pubsub.py.schema
  dm/templates/resource_policy/resource_policy.py.schema
  dm/templates/route/route.py.schema
  dm/templates/route/single_route.py.schema
  dm/templates/runtime_config/variable.py.schema
  dm/templates/runtime_config/waiter.py.schema
  dm/templates/shared_vpc_subnet_iam/shared_vpc_subnet_iam.py.schema
  dm/templates/ssl_certificate/ssl_certificate.py.schema
  dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py.schema
  dm/templates/stackdriver_notification_channels/stackdriver_notification_channels.py.schema
  dm/templates/target_proxy/target_proxy.py.schema
  dm/templates/unmanaged_instance_group/unmanaged_instance_group.py.schema
  dm/templates/url_map/url_map.py.schema
  dm/templates/vpn/vpn.py.schema
Labels: DM, bug, cla: yes

#872 Add external data for testing with Terraform BigQuery module
  infra/terraform/test-org/org/bigquery_external_data.tf
  infra/terraform/test-org/org/external_data/bar.csv
  infra/terraform/test-org/org/external_data/bigquery-external-table-test.csv
  infra/terraform/test-org/org/external_data/foo.csv
  infra/terraform/test-org/org/locals.tf
  infra/terraform/test-org/org/outputs.tf
Labels: cla: yes

#878 add hive partitioning support on bigquery_table dm template #877
  dm/templates/bigquery/bigquery_table.py
  dm/templates/bigquery/bigquery_table.py.schema
Labels: DM, cla: yes

#880 fix: Update test org iam cleaner to 0.13
  infra/terraform/test-org/org-iam-policy/cloudbuild.yaml
Labels: cla: yes
